#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#

#-----------------------------------------------------------------------
# Stages
#-----------------------------------------------------------------------

stages:
  - stage_1
  - stage_2
  - stage_3
  - stage_4
  - stage_5
  - stage_6
  - stage_7
  - stage_8
  - stage_9
  - stage_10
  - stage_11
  - stage_12
  - stage_13
  - stage_14
  - stage_15
  - stage_16
  - stage_17
  - stage_18
  - stage_19
  - stage_20

#-----------------------------------------------------------------------
# The .no_script job template
#-----------------------------------------------------------------------

.no_script:
  image: bash
  script:
    - ':'
  variables:
    GIT_STRATEGY: none

#-----------------------------------------------------------------------
# GitLab Pages
#-----------------------------------------------------------------------

build_pages:
  artifacts:
    paths:
      - public
  image: docker
  script:
    - build-aux/adock asciidoctor doc/manual/index.adoc
    - cp -R doc/manual public
    - cp -R doc/manual public/manual
  services:
    - docker:dind
  stage: stage_1

pages:
  extends:
    - .no_script
    - build_pages
  needs:
    - build_pages
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: stage_2

#-----------------------------------------------------------------------
