\input texinfo
@setfilename gatbps.info
@documentencoding UTF-8

@settitle GATBPS

@defindex sf
@defindex tm

@include CC0-1.0-copying.texi
@include math.texi

@titlepage
@title GATBPS
@vskip 0pt plus 1filll
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@shortcontents

@contents

@ifnottex
@node Top
@top GATBPS

This manual is for GATBPS@.
@end ifnottex

@menu
* Introduction::
* Running @t{gatbps}::
* Mathematical Notation in Texinfo::
* Special File Reference::
* CC0::
* Special File Index::
@end menu

@node Introduction
@chapter Introduction

GATBPS (pronunciation: gat-bee-pee-ESS)
provides a program named @t{gatbps}
that generates basic files for software packages@.
It was originally created to provide a small number
of shell scripts to be used with the GNU Autotools build
system, and its name stood for ``@b{G}NU @b{A}uto@b{t}ools
@b{B}oiler@b{p}late @b{S}cripts''@.
However, it quickly grew to provide other kinds of basic files,
and its name now stands for
``@b{G}ener@b{a}@b{t}e @b{B}asic @b{P}ackage @b{S}tuff''@.

@node Running @t{gatbps}
@chapter Running @t{gatbps}

@menu
* Options::
* Environment Variables::
@end menu

@node Options
@section Options

@table @asis
@item @t{--}
@itemx @w{}
The
@t{--}
option disables option detection, causing all
further arguments to be interpreted as operands@.

@item @t{--help}[@t{=}@i{S}]
@itemx @w{}
The
@t{--help}
and
@t{--help=}@i{S}
options write text to standard output
and cause all further arguments to be ignored@.
For the
@t{--help}
option, the text is
a short description of the program@.
For the
@t{--help=}@i{S}
option, the text is
a short description of the
file that would be generated by the
@t{gatbps@w{ }--@w{ }}@i{S}
command@.

@item @t{--man}
@itemx @w{}
The
@t{--man}
option writes text to standard output
and causes all further arguments to be ignored@.
The text is the source code of the program's
manual page, which can be processed with any
command that is analogous to the
@t{tbl@w{ }|@w{ }nroff@w{ }-man}
command@.

@item @t{--recursive}
@itemx @t{-r}
@itemx @w{}
Each
@t{--recursive}
option enables recursive dependency
generation, which is initially disabled@.

@item @t{--version}
@itemx @w{}
The
@t{--version}
option writes text to standard output
and causes all further arguments to be ignored@.
The text is the program's
name, package, version number,
release date, and copyright information@.
@end table

@node Environment Variables
@section Environment Variables

@table @asis
@item @t{AWK}
@itemx @w{}
If the
@t{AWK}
environment variable
is set to a nonempty string
@i{S},
then a
@t{--awk=}@i{S}
option is added to the
arguments at a position that
lies before all original arguments@.
Otherwise, the
@t{AWK}
environment variable has no effect@.

@item @t{SED}
@itemx @w{}
If the
@t{SED}
environment variable
is set to a nonempty string
@i{S},
then a
@t{--sed=}@i{S}
option is added to the
arguments at a position that
lies before all original arguments@.
Otherwise, the
@t{SED}
environment variable has no effect@.

@item @t{STYLE}
@itemx @w{}
If the
@t{STYLE}
environment variable
is set to a nonempty string
@i{S},
then a
@t{--style=}@i{S}
option is added to the
arguments at a position that
lies before all original arguments
and before the options added by the
@t{STYLE_STDERR}
and
@t{STYLE_STDOUT}
environment variables@.
Otherwise, the
@t{STYLE}
environment variable has no effect@.
@end table

@node Mathematical Notation in Texinfo
@chapter Mathematical Notation in Texinfo

GATBPS provides a collection of Texinfo
macros that support an alternative approach
to writing mathematical notation in Texinfo@.
The idea is to write each expression in both
raw @TeX{} and plain Texinfo syntax@.
For example:

@example
@@tex
$x + y$
@@end tex
@@ifnottex
@@i@{x@} + @@i@{y@}
@@end ifnottex
@end example

@noindent
The macros are then used in the
@t{@@ifnottex}
section to imitate @TeX{}@.
For example, the
@t{@@mdot}
macro imitates the
@t{\cdot}
control sequence@.
The macro names are chosen
to avoid collisions with the names of
Texinfo commands and @TeX{} control sequences,
as recommended by the Texinfo manual@.

@sfindex @t{math.@:texi}
Each macro
@t{@@}@i{M}
is defined by the
@i{M}@t{.@:texi}
special file, which also uses the
@i{M}@t{texi}
flag as an include guard so that including the
file multiple times is equivalent to including
it only the first time@.
For example, the
@t{@@mdot}
macro is defined by the
@t{mdot.@:texi}
special file, which also uses the
@t{mdottexi}
flag as an include guard@.
The
@t{math.@:texi}
special file is also provided, which uses
@t{@@include}
commands to include every
@i{M}@t{.@:texi}
special file@.
It can be generated with the
@t{--recursive}
option to also generate every
@i{M}@t{.@:texi}
special file at once@.

The macros insert symbols as
UTF-8 characters in Info and plain text and
as numeric character references in Docbook, HTML, and
XML by default, or as ASCII alternatives in
all output formats if the
@t{insertascii}
flag is set at their points of inclusion@.
For example, the
@t{@@mdot}
macro inserts a UTF-8 dot
operator character
in Info and plain text and an
@t{&#x22C5;}
character reference in Docbook, HTML, and
XML by default, or an ASCII
@t{*}
character in all output formats if the
@t{insertascii}
flag is set at its point of inclusion@.

In Docbook, HTML, and XML, the macros use the
@t{@@inlineraw}
command to insert numeric character references@.
This command was added in Texinfo 5.@:0,
which was released on 2013-02-16@.
The macros automatically detect older versions of
Texinfo, in which case they insert UTF-8 characters instead@.

The following table lists the macros that have
no parameters, which insert individual symbols@.
Along with each macro is its corresponding @TeX{}
syntax, the Unicode character that it inserts
by default, and the ASCII alternative that
it inserts if the
@t{insertascii}
flag is set at its point of inclusion@.
If this manual is translated to @TeX{}
or any other output format without the
@t{insertascii}
flag set, then the table also
shows the symbol of each macro@.

@quotation
@ifnottex
@ifset insertascii
@set HideSymbols
@end ifset
@end ifnottex
@ifset HideSymbols
@multitable {@t{\cdots}} {@t{@@mdots@{@}}} {Unicode} {ASCII}
@headitem @TeX{} @tab Macro @tab Unicode @tab ASCII
@item @t{-} @tab @t{@@msign@{@}} @tab U+2212 @tab @t{-}
@sfindex @t{msign.@:texi}
@tmindex @t{@@msign}
@item @t{\cdot} @tab @t{@@mdot@{@}} @tab U+22C5 @tab @t{*}
@sfindex @t{mdot.@:texi}
@tmindex @t{@@mdot}
@item @t{\cdots} @tab @t{@@mdots@{@}} @tab U+22EF @tab @t{.@:.@:.@:}
@sfindex @t{mdots.@:texi}
@tmindex @t{@@mdots}
@item @t{\ldots} @tab @t{@@bdots@{@}} @tab U+2026 @tab @t{.@:.@:.@:}
@sfindex @t{bdots.@:texi}
@tmindex @t{@@bdots}
@end multitable
@end ifset
@ifclear HideSymbols
@multitable {@t{\cdots}} {@t{@@mdots@{@}}} {Unicode} {ASCII} {Symbol}
@headitem @TeX{} @tab Macro @tab Unicode @tab ASCII @tab Symbol
@item @t{-} @tab @t{@@msign@{@}} @tab U+2212 @tab @t{-}
@sfindex @t{msign.@:texi}
@tmindex @t{@@msign}
@tab
@tex
$-$
@end tex
@ifnottex
@msign{}
@end ifnottex
@item @t{\cdot} @tab @t{@@mdot@{@}} @tab U+22C5 @tab @t{*}
@sfindex @t{mdot.@:texi}
@tmindex @t{@@mdot}
@tab
@tex
$\cdot$
@end tex
@ifnottex
@mdot{}
@end ifnottex
@item @t{\cdots} @tab @t{@@mdots@{@}} @tab U+22EF @tab @t{.@:.@:.@:}
@sfindex @t{mdots.@:texi}
@tmindex @t{@@mdots}
@tab
@tex
$\cdots$
@end tex
@ifnottex
@mdots{}
@end ifnottex
@item @t{\ldots} @tab @t{@@bdots@{@}} @tab U+2026 @tab @t{.@:.@:.@:}
@sfindex @t{bdots.@:texi}
@tmindex @t{@@bdots}
@tab
@tex
$\ldots$
@end tex
@ifnottex
@bdots{}
@end ifnottex
@end multitable
@end ifclear
@end quotation

@sfindex @t{sbs.@:texi}
@sfindex @t{sps.@:texi}
@tmindex @t{@@sbs}
@tmindex @t{@@sps}
The
@t{@@sps@{}@i{L}@t{@comma{} }@i{S}@t{@comma{} }@i{R}@t{@}}
and
@t{@@sbs@{}@i{L}@t{@comma{} }@i{S}@t{@comma{} }@i{R}@t{@}}
macros are provided for inserting
@i{S}
as a superscript or subscript@.
In Docbook,
@i{L}
and
@i{R}
are ignored and
@i{S}
is inserted inside a
@t{<superscript>}
or
@t{<subscript>}
element@.
In HTML and XML,
@i{L}
and
@i{R}
are ignored and
@i{S}
is inserted inside a
@t{<sup>}
or
@t{<sub>}
element@.
In Info and plain text, an ASCII
@t{^}
or
@t{_}
character is inserted, followed by
@i{L},
then
@i{S},
then
@i{R},
so that
@i{L}
and
@i{R}
act as parentheses around
@i{S}@.
Note that
@i{L}
and
@i{R}
can be left blank@.
For example, the following code produces
@tex
$x^{y + z_w}$
@end tex
@ifnottex
@i{x}@sps{(, @i{y} + @i{z}@sbs{, @i{w}, }, )}
@end ifnottex
@c Note that @ifinfo really means Info or plain text.
@ifinfo
in the current output format:
@end ifinfo
@c Note that @ifnotinfo really means not Info and not plain text.
@ifnotinfo
in the current output format and
@t{x^(y + z_w)}
in Info and plain text:
@end ifnotinfo

@example
@@tex
$x^@{y + z_w@}$
@@end tex
@@ifnottex
@@i@{x@}@@sps@{(, @@i@{y@} + @@i@{z@}@@sbs@{, @@i@{w@}, @}, )@}
@@end ifnottex
@end example

In Docbook, HTML, and XML, the
@t{@@sps}
and
@t{@@sbs}
macros use the
@t{@@inlineraw}
command to insert superscript and subscript elements@.
This command was added in Texinfo 5.@:0,
which was released on 2013-02-16@.
The macros automatically detect older versions of
Texinfo, in which case they behave
as if the output format were Info
or plain text instead@.

@node Special File Reference
@chapter Special File Reference

This section provides a short
description of each special file@.
Along with each short description is a reference to
where the corresponding full description can be found@.
The short descriptions are the same as those shown by the
@t{--help=}@i{S}
option@.

@table @asis
@sfindex @t{bdots.@:texi}
@tmindex @t{@@bdots}
@item @t{bdots.@:texi}
@itemx @w{}
The
@t{bdots.@:texi}
special file defines the
@t{@@bdots@{@}}
Texinfo macro, which imitates the
@t{\ldots}
@TeX{} math mode syntax@.
This can be used to imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$1, \ldots, n$
@@end tex
@@ifnottex
1, @@bdots@{@}, @@i@{n@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @t{math.@:texi}
@item @t{math.@:texi}
@itemx @w{}
The
@t{math.@:texi}
special file uses
@t{@@include}
commands to include all special
files that provide Texinfo macros for mathematical notation@.
This can be
generated with the
@t{--recursive}
option to also generate all such special files
at once@.

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @t{mdot.@:texi}
@tmindex @t{@@mdot}
@item @t{mdot.@:texi}
@itemx @w{}
The
@t{mdot.@:texi}
special file defines the
@t{@@mdot@{@}}
Texinfo macro, which imitates the
@t{\cdot}
@TeX{} math mode syntax@.
This can be used to imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x \cdot y$
@@end tex
@@ifnottex
@@i@{x@} @@mdot@{@} @@i@{y@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @t{mdots.@:texi}
@tmindex @t{@@mdots}
@item @t{mdots.@:texi}
@itemx @w{}
The
@t{mdots.@:texi}
special file defines the
@t{@@mdots@{@}}
Texinfo macro, which imitates the
@t{\cdots}
@TeX{} math mode syntax@.
This can be used to imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$1 + \cdots + n$
@@end tex
@@ifnottex
1 + @@mdots@{@} + @@i@{n@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @t{msign.@:texi}
@tmindex @t{@@msign}
@item @t{msign.@:texi}
@itemx @w{}
The
@t{msign.@:texi}
special file defines the
@t{@@msign@{@}}
Texinfo macro, which imitates the
@t{-}
@TeX{} math mode syntax@.
This can be used to imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x - y$
@@end tex
@@ifnottex
@@i@{x@} @@msign@{@} @@i@{y@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @t{sbs.@:texi}
@tmindex @t{@@sbs}
@item @t{sbs.@:texi}
@itemx @w{}
The
@t{sbs.@:texi}
special file defines the
@t{@@sbs@{}@i{L}@t{@comma{} }@i{S}@t{@comma{} }@i{R}@t{@}}
Texinfo macro, which inserts
@i{S}
as a subscript in the output formats other than @TeX{}@.
@i{L}
and
@i{R}
are ignored except in Info and plain text,
where they act as parentheses around
@i{S}@.
This can be used to imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x_@{y + z_w@}$
@@end tex
@@ifnottex
@@i@{x@}@@sbs@{(, @@i@{y@} + @@i@{z@}@@sbs@{, @@i@{w@}, @}, )@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @t{sps.@:texi}
@tmindex @t{@@sps}
@item @t{sps.@:texi}
@itemx @w{}
The
@t{sps.@:texi}
special file defines the
@t{@@sps@{}@i{L}@t{@comma{} }@i{S}@t{@comma{} }@i{R}@t{@}}
Texinfo macro, which inserts
@i{S}
as a superscript in the output formats other than @TeX{}@.
@i{L}
and
@i{R}
are ignored except in Info and plain text,
where they act as parentheses around
@i{S}@.
This can be used to imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x^@{y + z^w@}$
@@end tex
@@ifnottex
@@i@{x@}@@sps@{(, @@i@{y@} + @@i@{z@}@@sps@{, @@i@{w@}, @}, )@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.
@end table

@include CC0-1.0-appendix.texi

@node Special File Index
@unnumbered Special File Index

@printindex sf
@ifxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifxml
@bye
