@node @t{gatbps} Standard Error
@chapter @t{gatbps} Standard Error

Each error causes a message
to be written to standard error@.
Each line
of the message
is punctuated by either
an exclamation point, colon,
or full stop character, which
indicate fatal, cautionary, and
informational errors, respectively@.
The messages may
use escape sequences if
styling is in effect via the
@w{@t{-@w{-}style-stderr}}
option@.
Underlying programs
may also write messages to
standard error of their own volition@.
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
