@node @t{gatbps} Description
@chapter @t{gatbps} Description

@w{@t{gatbps}}
generates basic files
for software packages@.
The arguments are processed
one at a time from left to right@.
Each argument
is classified as
either an operand or
as (part of) an option@.
Each operand
generates a file,
and each option modifies the
overall behavior of the program@.
Each operand is
classified by its file
name as either special or plain@.
There is a fixed
list of special files,
and any other file is plain@.
A special file
has fixed content,
with examples including
copyright text and shell
scripts to help the build system@.
A plain file is
generated as the plain text
output of a corresponding Texinfo file,
which is useful for writing files like
@w{@t{README}}
and
@w{@t{INSTALL}}
in Texinfo@.
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
