\input texinfo
@setfilename gatbps.info
@documentencoding UTF-8

@settitle GATBPS

@include CC0-1.0-copying.texi
@include mdot.texi
@include mdots.texi

@titlepage
@title GATBPS
@vskip 0pt plus 1filll
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@shortcontents

@contents

@ifnottex
@node Top
@top GATBPS

This manual is for GATBPS@.
@end ifnottex

@menu
* Introduction::
* Mathematical Notation in Texinfo::
* CC0::
@end menu

@node Introduction
@chapter Introduction

GATBPS (pronunciation: gat-bee-pee-ESS)
provides a program named @t{gatbps}
that generates basic files for software packages@.
It was originally created to provide a small number
of shell scripts to be used with the GNU Autotools build
system, and its name stood for ``@b{G}NU @b{A}uto@b{t}ools
@b{B}oiler@b{p}late @b{S}cripts''@.
However, it quickly grew to provide other kinds of basic files,
and its name now stands for
``@b{G}ener@b{a}@b{t}e @b{B}asic @b{P}ackage @b{S}tuff''@.

@node Mathematical Notation in Texinfo
@chapter Mathematical Notation in Texinfo

GATBPS provides a collection of Texinfo
macros that support an alternative approach
to writing mathematical notation in Texinfo@.
The idea is to write each expression in both
raw @TeX{} and plain Texinfo syntax, like this:

@example
@@tex
$x + y$
@@end tex
@@ifnottex
@@i@{x@} + @@i@{y@}
@@end ifnottex
@end example

@noindent
The macros are then used in the
@t{@@ifnottex}
section to imitate @TeX{}@.
For example, the
@t{@@mdot@{@}}
macro imitates the
@t{\cdot}
control sequence@.
As recommended by the Texinfo manual,
the macro names are carefully chosen
to avoid collisions with the names of
Texinfo commands and @TeX{} control sequences@.

Each macro
@i{M}
is defined by the
@i{M}@t{.texi}
special file@.
For example, the
@t{@@mdot@{@}}
macro is defined by the
@t{mdot.texi}
special file@.
The
@t{math.texi}
special file is also provided, which uses
@t{@@include}
commands to include the entire collection of macros@.
It can be generated with the
@t{--walk}
option to generate the entire collection at once@.

The macros insert UTF-8 characters in
the Info and plain text output formats
and character references in the Docbook,
HTML, and XML output formats for special
glyphs by default, but they can be configured
to insert ASCII approximations by setting the
@t{ASCII}
flag before their inclusion@.
For example, the
@t{@@mdot@{@}}
macro inserts a dot operator character (U+22C5)
in the Info and plain text output formats and an
@t{&sdot;}
character reference in the Docbook, HTML,
and XML output formats by default, but it
inserts an asterisk character (U+002A) in
all output formats if the
@t{ASCII}
flag is set@.

The following table lists the macros that have
no parameters, which insert individual glyphs@.
Along with each macro is its corresponding @TeX{}
syntax, the number of the Unicode character that it
inserts by default (either literally in the Info and
plain text output formats or as a character reference
in the Docbook, HTML, and XML output formats), and the
ASCII approximation that it inserts if the
@t{ASCII}
flag is set@.
If this manual is typeset as @TeX{}
or any other output format without the
@t{ASCII}
flag set, then the glyphs are also shown@.

@indentedblock
@ifnottex
@ifset ASCII
@set HideGlyphs
@end ifset
@end ifnottex
@ifset HideGlyphs
@multitable {@t{\cdots}} {@t{@@mdots@{@}}} {Unicode} {ASCII}
@headitem @TeX{} @tab Macro @tab Unicode @tab ASCII
@item @t{\cdot} @tab @t{@@mdot@{@}} @tab U+22C5 @tab @t{*}
@item @t{\cdots} @tab @t{@@mdots@{@}} @tab U+22EF @tab @t{.@:.@:.@:}
@end multitable
@end ifset
@ifclear HideGlyphs
@multitable {@t{\cdots}} {@t{@@mdots@{@}}} {Unicode} {ASCII} {Glyph}
@headitem @TeX{} @tab Macro @tab Unicode @tab ASCII @tab Glyph
@item @t{\cdot} @tab @t{@@mdot@{@}} @tab U+22C5 @tab @t{*}
@tab
@tex
$\cdot$
@end tex
@ifnottex
@mdot{}
@end ifnottex
@item @t{\cdots} @tab @t{@@mdots@{@}} @tab U+22EF @tab @t{.@:.@:.@:}
@tab
@tex
$\cdots$
@end tex
@ifnottex
@mdots{}
@end ifnottex
@end multitable
@end ifclear
@end indentedblock

@include CC0-1.0-appendix.texi
@iftex
@ifnottex
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnottex
@end iftex
@bye
