@node @t{gatbps} Description
@chapter @t{gatbps} Description

@w{@t{gatbps}}
generates basic files
for software packages@.
The arguments
are processed one
at a time, in order@.
Each argument
is classified as
either an operand or
as (part of) an option@.
Each operand
generates a file,
and each option changes the
overall behavior of the program@.
Each operand is
classified by its file
name as either special or plain@.
There is a fixed
list of special files,
and any other file is plain@.
Each special file
is fixed in content,
with examples including
copyright texts and scripts
to be used with the build system@.
Each plain file is
generated as the plain text
output of a corresponding Texinfo file,
which is useful for writing files like
@w{@t{README}}
and
@w{@t{INSTALL}}
in Texinfo@.

Each operand is
processed in three phases:
printing, generation, and recursion@.
Printing writes the
operand to standard output,
generation actually creates the file,
and recursion, which only applies to
special files, prepends any prerequisite
special files to the remaining arguments@.
Various options
can be used to enable
or disable each phase,
but printing and generation
cannot be simultaneously disabled@.
By default, only generation is enabled@.

Options are written
in the usual GNU style@.
Each option has
one or more names, and each
name is either long or short@.
A long name consists of
two hyphen-minus characters
followed by zero or more printable
characters except for the space character,
and a short name consists of one hyphen-minus
character followed by one printable character
except for the hyphen-minus and space characters@.
An option either requires a value,
permits a value, or forbids a value@.
Let
@w{@t{-@w{-}}@i{L}}
and
@w{@t{-}@i{S}}
be long and short names for an option and
@w{@i{V}}
be a value@.
If the option
requires a value,
then it may be written as
@w{@t{-@w{-}}@i{L}@t{=}@i{V}@comma{}}
@w{@t{-@w{-}}@i{L@w{ }V}@comma{}}
@w{@t{-}@i{SV}@comma{}}
or
@w{@t{-}@i{S@w{ }V}@.}
If the option
permits a value,
then it may be written as
@w{@t{-@w{-}}@i{L}@t{=}@i{V}@comma{}}
@w{@t{-@w{-}}@i{L}@comma{}}
@w{@t{-}@i{SV}@comma{}}
or
@w{@t{-}@i{S}@.}
If the option
forbids a value,
then it may be written as
@w{@t{-@w{-}}@i{L}}
or
@w{@t{-}@i{S}@.}
Furthermore, a short name argument
@w{@t{-}@i{T}}
for an option
that forbids a value
may be (repeatedly) combined
with any immediately following
@w{@t{-}@i{S}}
form by deleting the
@w{@t{-}@i{T}}
argument and inserting
@w{@i{T}}
between the
@w{@t{-}}
and
@w{@i{S}}
characters@.
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
