@node Basic Package Types
@chapter Basic Package Types

@noindent
GATBPS is available in three different package formats: as a copy of the
Git repository, as a source archive, and as a distribution archive@.
The Git repository is the definitive copy of the package, a source
archive is a snapshot of the Git repository at a specific moment in
history, and a distribution archive is a source archive that has been
optimized for building and installation@.
The differences between the package formats are discussed throughout
this manual, but they are particularly relevant to building and
installation@.

@include indent.texi
If you are not sure which package format you are working with, then you
can distinguish them as follows:

@enumerate
@item
If there is a subdirectory named
@w{@t{.@:git}}
in the directory that contains the
@w{@t{configure.@:ac}}
file, then you are working with a copy of the Git repository@.

@item
Otherwise, if there is a subdirectory named
@w{@t{dev-aux}}
in the directory that contains the
@w{@t{configure.@:ac}}
file, then you are working with a source archive@.

@item
Otherwise, you are working with a distribution archive@.
@end enumerate

@include indent.texi
If you are only interested in building and installing the package, then
you probably want to work with a distribution archive@.
Distribution archives are optimized for building and installation@.

@include indent.texi
If you are only interested in browsing the source code of the package,
then you probably want to work with a copy of the Git repository or a
source archive@.
Distribution archives include generated source code and may exclude some
of the normal source code@.

@include indent.texi
If you are interested in modifying the source code of the package, then
you probably want to work with a copy of the Git repository@.
Copies of the Git repository provide version control and include the
complete development history of the package@.
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
