@node Build System Initialization
@chapter Build System Initialization

@noindent
If you are working with the Git repository or a tree archive, then the
first step is to initialize the build system@.
If you are working with a distribution archive, then you should skip
this step, as the build system is already initialized@.
To initialize the build system, run the following command after making
sure that you have the GNU Autotools installed:

@example
./autogen
@end example
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
