@ifset fullmanual
@node Building and Installation
@chapter Building and Installation
@end ifset
@ifclear fullmanual
@unnumbered Building and Installation
@end ifclear

@noindent
GATBPS uses the GNU build system for building and installation@.

@menu
* Package Formats::
* Build System Initialization::
* Required Packages::
* Configuration::
* Building::
* Installation::
@end menu

@lowersections
@include gatbps/Package-Formats.texi

@include gatbps/Build-System-Initialization.texi

@include gatbps/Required-Packages.texi

@include gatbps/Configuration.texi

@include gatbps/Building.texi

@include gatbps/Installation.texi
@raisesections
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
