@node Checking for Missing Autoconf Macros
@chapter Checking for Missing Autoconf Macros

@noindent
GATBPS provides a number of special files that define Autoconf macros@.
The files follow the
@w{@t{aclocal}}
conventions, with each file defining a main macro and zero or more
helper macros that are intended to be used only by the main macro@.
You can selectively include only the files that you need, but some main
macros depend on other main macros, so you must remember to include the
files for those macros too@.
You can list these dependencies with the
@w{@t{-@w{-}dry-run}}
and
@w{@t{-@w{-}recursive}}
options of the
@w{@t{gatbps}}
program, but it is still easy to make mistakes@.

@include indent.texi
Missing macros usually result in Autoconf copying the unexpanded macro
calls to the
@w{@t{configure}}
script and succeeding without warnings, as Autoconf does not know that
you were expecting the macros to be defined and therefore does not see
the problem@.
Sometimes the resulting
@w{@t{configure}}
script will fail with an error message that helps you find the problem@.
For example, consider the following
@w{@t{configure.@:ac}}
file:

@example
AC_INIT([foo], [1.0])
bar([baz])
AC_OUTPUT
@end example

@noindent
Because the
@w{@t{bar}}
macro is not defined, the resulting
@w{@t{configure}}
script will contain a
``@w{@t{bar(baz)}}''@tie{}line
and will probably fail with an error message like this:

@example
./configure: line 1664: syntax error near unexpected token `baz'
./configure: line 1664: `bar(baz)'
@end example

GATBPS provides a system that can catch such mistakes at Autoconf time@.
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
