@node Checking for Missing Autoconf Macros
@chapter Checking for Missing Autoconf Macros

@noindent
GATBPS provides a number of special files that define Autoconf macros@.
Each file defines one main macro and zero or more helper macros that
help implement the main macro@.
You can selectively include only the files that you need, but some main
macros depend on other main macros, so you must remember to include the
files for those macros too@.
You can list the dependencies with the
@w{@t{-@w{-}dry-run}}
and
@w{@t{-@w{-}recursive}}
options of the
@w{@t{gatbps}}
program, but it is still easy to make mistakes@.

@include indent.texi
Missing macros normally result in Autoconf copying the unexpanded macro
calls to the
@w{@t{configure}}
script and succeeding without warnings, as Autoconf does not know that
you were expecting the macros to be defined and therefore does not see
the problem@.
However, depending on the exact text of the unexpanded macro calls, the
resulting
@w{@t{configure}}
script may fail with an error message that helps you find the problem@.
For example, consider the following
@w{@t{configure.@:ac}}
file:

@example
AC_INIT([foo], [1.0])
bar([baz])
AC_OUTPUT
@end example

@noindent
Because the
@w{@t{bar}}
macro is not defined, the resulting
@w{@t{configure}}
script will contain a line that contains
exactly@tie{}``@w{@t{bar(baz)}}'',
so the script will probably fail with an error message like this:

@example
./configure: line 1664: syntax error near unexpected token `baz'
./configure: line 1664: `bar(baz)'
@end example

GATBPS provides a system that can catch such mistakes at Autoconf time@.

Add the following line to your
@w{@t{configure.@:ac}}
file just after calling the
@w{@t{AC_INIT}}
macro:

@example
gatbps_check_macros || exit $?
@end example

If you have not included any GATBPS macros or not called any that you
have included, then Autoconf will succeed and the
@w{@t{configure}}
script will fail with a message like this:

@example
./configure: line 1664: gatbps_check_macros: command not found
@end example

@example
AC_DEFUN([foo_check_macros], [dnl
gatbps_check_macros_code(
  [bar],
  [])[]dnl
]m4_define(
  [gatbps_check_macros],
  m4_ifndef(
    [gatbps_check_macros],
    [[[# gatbps_check_macros]]],
    [m4_defn([gatbps_check_macros])])[dnl
foo_check_macros[]dnl
]))[]dnl
AC_DEFUN([foo], [dnl
foo_check_macros[]dnl
...
])[]dnl
@end example
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
