@node Installation
@chapter Installation

@noindent
The Info directory entries for the manual follow the standard formatting
conventions, which include starting program descriptions on the
49th@tie{}column
and other descriptions on the
33rd@tie{}column@.
However, installation reformats the entries by default, which may move
some of the program descriptions to the
33rd@tie{}column@.
This can be prevented by setting the
@w{@t{INSTALL_INFO_NO_INDENT}}
environment variable to any value during the
@w{@t{make install}}
command@.
For example, the following command might be used:

@example
sudo INSTALL_INFO_NO_INDENT=yes make install
@end example
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
