@node Special File Reference
@chapter Special File Reference

This section provides a short
description of each special file@.
Along with each
short description is a
cross-reference to where the
full description can be found@.
If a special file
supports comments,
then its short description is also
included in a comment at the top of the file@.
The short descriptions can
also be shown by using the
@w{@t{-@w{-}help=}@i{S}}
option of
@w{@t{gatbps}}@.

@table @asis
@sfindex @w{@t{CC0-1.@:0-AC-COPYRIGHT.@:ac}}
@item @w{@t{CC0-1.@:0-AC-COPYRIGHT.@:ac}}
@include ipez.texi
The
@w{@t{CC0-1.@:0-AC-COPYRIGHT.@:ac}}
special file calls the
@w{@t{AC_COPYRIGHT}}
Autoconf macro with a message stating that some parts of the script
are from the package and that the authors of those parts have waived
their rights to them by referencing the
@w{@t{CC0-1.@:0.@:txt}}
special file@.
It can be included in an Autoconf file where the
@w{@t{AC_COPYRIGHT}}
call is desired to occur@.

@sfindex @w{@t{CC0-1.@:0-appendix.@:texi}}
@item @w{@t{CC0-1.@:0-appendix.@:texi}}
@include ipez.texi
The
@w{@t{CC0-1.@:0-appendix.@:texi}}
special file is a Texinfo appendix that contains the complete text of
the Creative Commons Zero
(CC0)@tie{}1.@:0
Universal Public Domain Dedication@.
It can be included in a Texinfo document where the appendix is desired
to appear@.
The appendix is labeled with
@w{@t{@@node}}
@w{@t{Creative}}
@w{@t{Commons}}
@w{@t{Zero@@tie@{@}@@w@{1-0@}}}
so that it maintains the usual node structure and can be
cross-referenced@.

For more information, @pxref{Copyright Texts}@.

@sfindex @w{@t{CC0-1.@:0-commit.@:txt}}
@item @w{@t{CC0-1.@:0-commit.@:txt}}
@include ipez.texi
The
@w{@t{CC0-1.@:0-commit.@:txt}}
special file is a commit
message template that states that
the author of the commit has waived
their rights to it by cross-referencing the
@w{@t{CC0-1.@:0.@:txt}}
special file@.
This can be used, for example, with Git's
@w{@t{commit.@:template}}
configuration variable@.

For more information, @pxref{Copyright Texts}@.

@sfindex @w{@t{CC0-1.@:0-copying.@:texi}}
@item @w{@t{CC0-1.@:0-copying.@:texi}}
@include ipez.texi
The
@w{@t{CC0-1.@:0-copying.@:texi}}
special file invokes the
@w{@t{@@copying}}
Texinfo command with a message stating that the authors of the manual
have waived their rights to it by cross-referencing the appendix of the
@w{@t{CC0-1.@:0-appendix.@:texi}}
special file@.
It can be included in a Texinfo document where the invocation of the
@w{@t{@@copying}}
command is desired to occur@.

For more information, @pxref{Copyright Texts}@.

@sfindex @w{@t{CC0-1.@:0-file.@:txt}}
@item @w{@t{CC0-1.@:0-file.@:txt}}
@include ipez.texi
The
@w{@t{CC0-1.@:0-file.@:txt}}
special file contains
a message stating that the
authors of the file have waived their
rights to it by cross-referencing the
@w{@t{CC0-1.@:0.@:txt}}
special file@.
This can be used
as a copyright notice
in a wide variety of files@.

For more information, @pxref{Copyright Texts}@.

@sfindex @w{@t{CC0-1.@:0.@:txt}}
@item @w{@t{CC0-1.@:0.@:txt}}
@include ipez.texi
The
@w{@t{CC0-1.@:0.@:txt}}
special file is the
plain text version of the
Creative Commons Zero (CC0) 1.@:0
Universal Public Domain Dedication@.

For more information, @pxref{Copyright Texts}@.

@sfindex @w{@t{TEST_EXIT.@:h}}
@item @w{@t{TEST_EXIT.@:h}}
@include ipez.texi
The
@w{@t{TEST_EXIT.@:h}}
special file is a C header file that defines the
@w{@t{TEST_EXIT_ERROR}},
@w{@t{TEST_EXIT_FAIL}},
@w{@t{TEST_EXIT_PASS}},
and
@w{@t{TEST_EXIT_SKIP}}
macros to
@w{@t{99}},
@w{@t{1}},
@w{@t{0}},
and
@w{@t{77}},
respectively@.
These are the exit status values used by GNU Automake for a test suite
with no test protocol@.

@sfindex @w{@t{barrow.@:texi}}
@tmindex @w{@t{@@barrow}}
@item @w{@t{barrow.@:texi}}
@include ipez.texi
The
@w{@t{barrow.@:texi}}
special file defines the
@w{@t{@@barrow}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$P \leftrightarrow Q$
@@end tex
@@ifnottex
@@w@{@@i@{P@} @@barrow@{@} @@i@{Q@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{bdarrow.@:texi}}
@tmindex @w{@t{@@bdarrow}}
@item @w{@t{bdarrow.@:texi}}
@include ipez.texi
The
@w{@t{bdarrow.@:texi}}
special file defines the
@w{@t{@@bdarrow}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$P \Leftrightarrow Q$
@@end tex
@@ifnottex
@@w@{@@i@{P@} @@bdarrow@{@} @@i@{Q@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{bdots.@:texi}}
@tmindex @w{@t{@@bdots}}
@item @w{@t{bdots.@:texi}}
@include ipez.texi
The
@w{@t{bdots.@:texi}}
special file defines the
@w{@t{@@bdots}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$1, \ldots, n$
@@end tex
@@ifnottex
@@w@{1@@comma@{@} @@bdots@{@}@@comma@{@} @@i@{n@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{dprm.@:texi}}
@tmindex @w{@t{@@dprm}}
@item @w{@t{dprm.@:texi}}
@include ipez.texi
The
@w{@t{dprm.@:texi}}
special file defines the
@w{@t{@@dprm}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$x'@w{'}$
@@end tex
@@ifnottex
@@w@{@@i@{x@}@@dprm@{@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{dslash.@:texi}}
@tmindex @w{@t{@@dslash}}
@item @w{@t{dslash.@:texi}}
@include ipez.texi
The
@w{@t{dslash.@:texi}}
special file defines the
@w{@t{@@dslash}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$x / y$
@@end tex
@@ifnottex
@@w@{@@i@{x@} @@dslash@{@} @@i@{y@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{gequ.@:texi}}
@tmindex @w{@t{@@gequ}}
@item @w{@t{gequ.@:texi}}
@include ipez.texi
The
@w{@t{gequ.@:texi}}
special file defines the
@w{@t{@@gequ}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$x \ge y$
@@end tex
@@ifnottex
@@w@{@@i@{x@} @@gequ@{@} @@i@{y@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{larrow.@:texi}}
@tmindex @w{@t{@@larrow}}
@item @w{@t{larrow.@:texi}}
@include ipez.texi
The
@w{@t{larrow.@:texi}}
special file defines the
@w{@t{@@larrow}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$P \leftarrow Q$
@@end tex
@@ifnottex
@@w@{@@i@{P@} @@larrow@{@} @@i@{Q@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{lbarrow.@:texi}}
@tmindex @w{@t{@@lbarrow}}
@item @w{@t{lbarrow.@:texi}}
@include ipez.texi
The
@w{@t{lbarrow.@:texi}}
special file defines the
@w{@t{@@lbarrow}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$P \longleftrightarrow Q$
@@end tex
@@ifnottex
@@w@{@@i@{P@} @@lbarrow@{@} @@i@{Q@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{lbdarrow.@:texi}}
@tmindex @w{@t{@@lbdarrow}}
@item @w{@t{lbdarrow.@:texi}}
@include ipez.texi
The
@w{@t{lbdarrow.@:texi}}
special file defines the
@w{@t{@@lbdarrow}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$P \Longleftrightarrow Q$
@@end tex
@@ifnottex
@@w@{@@i@{P@} @@lbdarrow@{@} @@i@{Q@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{lcei.@:texi}}
@tmindex @w{@t{@@lcei}}
@item @w{@t{lcei.@:texi}}
@include ipez.texi
The
@w{@t{lcei.@:texi}}
special file defines the
@w{@t{@@lcei}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$\lceil x \rceil$
@@end tex
@@ifnottex
@@w@{@@lcei@{@}@@i@{x@}@@rcei@{@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{ldarrow.@:texi}}
@tmindex @w{@t{@@ldarrow}}
@item @w{@t{ldarrow.@:texi}}
@include ipez.texi
The
@w{@t{ldarrow.@:texi}}
special file defines the
@w{@t{@@ldarrow}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$P \Leftarrow Q$
@@end tex
@@ifnottex
@@w@{@@i@{P@} @@ldarrow@{@} @@i@{Q@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{lequ.@:texi}}
@tmindex @w{@t{@@lequ}}
@item @w{@t{lequ.@:texi}}
@include ipez.texi
The
@w{@t{lequ.@:texi}}
special file defines the
@w{@t{@@lequ}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$x \le y$
@@end tex
@@ifnottex
@@w@{@@i@{x@} @@lequ@{@} @@i@{y@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{lflo.@:texi}}
@tmindex @w{@t{@@lflo}}
@item @w{@t{lflo.@:texi}}
@include ipez.texi
The
@w{@t{lflo.@:texi}}
special file defines the
@w{@t{@@lflo}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$\lfloor x \rfloor$
@@end tex
@@ifnottex
@@w@{@@lflo@{@}@@i@{x@}@@rflo@{@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{llarrow.@:texi}}
@tmindex @w{@t{@@llarrow}}
@item @w{@t{llarrow.@:texi}}
@include ipez.texi
The
@w{@t{llarrow.@:texi}}
special file defines the
@w{@t{@@llarrow}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$P \longleftarrow Q$
@@end tex
@@ifnottex
@@w@{@@i@{P@} @@llarrow@{@} @@i@{Q@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{lldarrow.@:texi}}
@tmindex @w{@t{@@lldarrow}}
@item @w{@t{lldarrow.@:texi}}
@include ipez.texi
The
@w{@t{lldarrow.@:texi}}
special file defines the
@w{@t{@@lldarrow}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$P \Longleftarrow Q$
@@end tex
@@ifnottex
@@w@{@@i@{P@} @@lldarrow@{@} @@i@{Q@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{lrarrow.@:texi}}
@tmindex @w{@t{@@lrarrow}}
@item @w{@t{lrarrow.@:texi}}
@include ipez.texi
The
@w{@t{lrarrow.@:texi}}
special file defines the
@w{@t{@@lrarrow}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$P \longrightarrow Q$
@@end tex
@@ifnottex
@@w@{@@i@{P@} @@lrarrow@{@} @@i@{Q@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{lrdarrow.@:texi}}
@tmindex @w{@t{@@lrdarrow}}
@item @w{@t{lrdarrow.@:texi}}
@include ipez.texi
The
@w{@t{lrdarrow.@:texi}}
special file defines the
@w{@t{@@lrdarrow}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$P \Longrightarrow Q$
@@end tex
@@ifnottex
@@w@{@@i@{P@} @@lrdarrow@{@} @@i@{Q@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{math.@:texi}}
@item @w{@t{math.@:texi}}
@include ipez.texi
The
@w{@t{math.@:texi}}
special file is a Texinfo file
that includes every special file
that defines a macro for imitating
the mathematical notation of @TeX{} in
the other output formats@.

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{mdot.@:texi}}
@tmindex @w{@t{@@mdot}}
@item @w{@t{mdot.@:texi}}
@include ipez.texi
The
@w{@t{mdot.@:texi}}
special file defines the
@w{@t{@@mdot}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$x \cdot y$
@@end tex
@@ifnottex
@@w@{@@i@{x@} @@mdot@{@} @@i@{y@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{mdots.@:texi}}
@tmindex @w{@t{@@mdots}}
@item @w{@t{mdots.@:texi}}
@include ipez.texi
The
@w{@t{mdots.@:texi}}
special file defines the
@w{@t{@@mdots}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$1 + \cdots + n$
@@end tex
@@ifnottex
@@w@{1 + @@mdots@{@} + @@i@{n@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{msign.@:texi}}
@tmindex @w{@t{@@msign}}
@item @w{@t{msign.@:texi}}
@include ipez.texi
The
@w{@t{msign.@:texi}}
special file defines the
@w{@t{@@msign}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$x - y$
@@end tex
@@ifnottex
@@w@{@@i@{x@} @@msign@{@} @@i@{y@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{nequ.@:texi}}
@tmindex @w{@t{@@nequ}}
@item @w{@t{nequ.@:texi}}
@include ipez.texi
The
@w{@t{nequ.@:texi}}
special file defines the
@w{@t{@@nequ}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$x \ne y$
@@end tex
@@ifnottex
@@w@{@@i@{x@} @@nequ@{@} @@i@{y@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{prm.@:texi}}
@tmindex @w{@t{@@prm}}
@item @w{@t{prm.@:texi}}
@include ipez.texi
The
@w{@t{prm.@:texi}}
special file defines the
@w{@t{@@prm}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$x'$
@@end tex
@@ifnottex
@@w@{@@i@{x@}@@prm@{@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{qprm.@:texi}}
@tmindex @w{@t{@@qprm}}
@item @w{@t{qprm.@:texi}}
@include ipez.texi
The
@w{@t{qprm.@:texi}}
special file defines the
@w{@t{@@qprm}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$x'@w{'}'@w{'}$
@@end tex
@@ifnottex
@@w@{@@i@{x@}@@qprm@{@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{rarrow.@:texi}}
@tmindex @w{@t{@@rarrow}}
@item @w{@t{rarrow.@:texi}}
@include ipez.texi
The
@w{@t{rarrow.@:texi}}
special file defines the
@w{@t{@@rarrow}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$P \rightarrow Q$
@@end tex
@@ifnottex
@@w@{@@i@{P@} @@rarrow@{@} @@i@{Q@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{rcei.@:texi}}
@tmindex @w{@t{@@rcei}}
@item @w{@t{rcei.@:texi}}
@include ipez.texi
The
@w{@t{rcei.@:texi}}
special file defines the
@w{@t{@@rcei}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$\lceil x \rceil$
@@end tex
@@ifnottex
@@w@{@@lcei@{@}@@i@{x@}@@rcei@{@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{rdarrow.@:texi}}
@tmindex @w{@t{@@rdarrow}}
@item @w{@t{rdarrow.@:texi}}
@include ipez.texi
The
@w{@t{rdarrow.@:texi}}
special file defines the
@w{@t{@@rdarrow}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$P \Rightarrow Q$
@@end tex
@@ifnottex
@@w@{@@i@{P@} @@rdarrow@{@} @@i@{Q@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{rflo.@:texi}}
@tmindex @w{@t{@@rflo}}
@item @w{@t{rflo.@:texi}}
@include ipez.texi
The
@w{@t{rflo.@:texi}}
special file defines the
@w{@t{@@rflo}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$\lfloor x \rfloor$
@@end tex
@@ifnottex
@@w@{@@lflo@{@}@@i@{x@}@@rflo@{@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{sbs.@:texi}}
@tmindex @w{@t{@@sbs}}
@item @w{@t{sbs.@:texi}}
@include ipez.texi
The
@w{@t{sbs.@:texi}}
special file defines the
@w{@t{@@sbs@{}@i{L}@t{@comma{} }@i{S}@t{@comma{} }@i{R}@t{@}}}
Texinfo macro, which inserts
@w{@i{S}}
as a subscript in the output formats other than @TeX{}@.
@w{@i{L}}
and
@w{@i{R}}
are ignored except in Info and plain text,
in which they are inserted to the left and right of
@w{@i{S}},
serving as parentheses@.
This is used to imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x_@{y + z_w@}$
@@end tex
@@ifnottex
@@w@{@@i@{x@}@@sbs@{(,@@i@{y@} + @@i@{z@}@@sbs@{,@@i@{w@},@},)@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{sps.@:texi}}
@tmindex @w{@t{@@sps}}
@item @w{@t{sps.@:texi}}
@include ipez.texi
The
@w{@t{sps.@:texi}}
special file defines the
@w{@t{@@sps@{}@i{L}@t{@comma{} }@i{S}@t{@comma{} }@i{R}@t{@}}}
Texinfo macro, which inserts
@w{@i{S}}
as a superscript in the output formats other than @TeX{}@.
@w{@i{L}}
and
@w{@i{R}}
are ignored except in Info and plain text,
in which they are inserted to the left and right of
@w{@i{S}},
serving as parentheses@.
This is used to imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x^@{y + z^w@}$
@@end tex
@@ifnottex
@@w@{@@i@{x@}@@sps@{(,@@i@{y@} + @@i@{z@}@@sps@{,@@i@{w@},@},)@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.

@sfindex @w{@t{texinfo.@:css}}
@item @w{@t{texinfo.@:css}}
@include ipez.texi
The
@w{@t{texinfo.@:css}}
special file is a CSS file that makes Texinfo's HTML output look more
like its
@TeX{}
output@.
It can be copied into the HTML output by using the
@w{@t{-@w{-}css-include}}
option of the
@w{@t{texi2any}}
program@.

@sfindex @w{@t{tprm.@:texi}}
@tmindex @w{@t{@@tprm}}
@item @w{@t{tprm.@:texi}}
@include ipez.texi
The
@w{@t{tprm.@:texi}}
special file defines the
@w{@t{@@tprm}}
Texinfo macro, which can be used to imitate the mathematical notation of
@TeX{}
in the other output formats@.
For example:

@example
@@tex
$x'@w{'}'$
@@end tex
@@ifnottex
@@w@{@@i@{x@}@@tprm@{@}@}
@@end ifnottex
@end example

For more information,
@pxref{Writing Mathematical Notation in Texinfo}@.
@end table
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
