#
# This file was generated by GATBPS 0.1.0-5854+g8b7b232f, which was
# released on 2021-10-03. Before changing it, make sure
# you're doing the right thing. Depending on how GATBPS
# is being used, your changes may be automatically lost.
# A short description of this file follows.
#
# Special file: gatbps-echo.sh
#
# For more information, see the GATBPS manual.
#

# TODO: We could support quoting for languages other than sh, like for
# awk for example, via syntax like sh gatbps-echo.sh --awk -q. Then we can
# remove awk-form.sh and any other *-form.sh scripts. Make sure to also
# support --sh for consistency. And maybe something like -Q to reset
# quoting_level back to 0.



#-----------------------------------------------------------------------
# Locale
#-----------------------------------------------------------------------
#
# With LC_ALL=C, locale-aware programs use the C locale instead of the
# current locale. This is generally the best approach for code that is
# not deliberately designed to work in other locales, as other locales
# may have surprising behavior. The locale affects many programs, like
# awk, grep, sed, and this shell instance itself. For more information,
# see the C standard, the POSIX standard, and the GNU C Library manual.
#

LC_ALL=C
export LC_ALL

#-----------------------------------------------------------------------
# Newline characters
#-----------------------------------------------------------------------
#
# The nl variable holds a newline character. It can be used where a
# literal newline character might be awkward.
#

nl='
'
readonly nl

#-----------------------------------------------------------------------
# gatbps_barf
#-----------------------------------------------------------------------

gatbps_barf() {
  case $# in 0)
    printf '%s\n' "$0: Error: Unknown error." >&2
  ;; 1)
    printf '%s\n' "$0: Error: $1" >&2
  ;; *)
    printf '%s' "$0: Error: $1" >&2
    shift
    printf ' %s' "$@" >&2
    echo >&2
  esac
  exit 1
}

#-----------------------------------------------------------------------

readonly sh_quote_script="
  s/'/'\\\\''/g
  1 s/^/'/
  \$ s/\$/'/
"

parse_options=:

gatbps_unknown_opt() {
  case $1 in --*)
    printf '%s' "$0: Unknown option: " >&2
    sed '
      /=/ {
        s/=.*//
        q
      }
    ' <<EOF2 >&2
$1
EOF2
    exit 1
  ;; -?*)
    printf '%s: Unknown option: %.2s\n' "$0" "$1" >&2
    exit 1
  esac
}

#-----------------------------------------------------------------------



SED=${SED:-sed}
readonly SED

quoting_level=0
first_operand=:
output=

process_operand() {

  if $first_operand; then
    first_operand=false
  else
    output=$output' '
  fi

  case $quoting_level in
    -* | 0)
      output=$output$1
    ;;
    1)
      case $1 in
        '' | *[!+./0-9:=A-Z_a-z-]*)
          output=$output`eval " $SED"' "$sh_quote_script" <<EOF2
$1
EOF2
          '` || exit
        ;;
        *)
          output=$output$1
        ;;
      esac
    ;;
    *)
      output=$output`eval " $SED"' "$sh_quote_script" <<EOF2
$1
EOF2
      '` || exit
    ;;
  esac

}

until (exit ${1+1}0); do

  if $parse_options; then
    case $1 in

      #-----------------------------------------------------------------
      # Options terminator
      #-----------------------------------------------------------------

      --)
        parse_options=false
        shift
        continue
      ;;

      --=*)
        cat <<EOF2 >&2
${fr2}gatbps-echo.sh!${fR2} ${fB2}--${fR2} forbids a value
${fr2}gatbps-echo.sh!${fR2} try ${fB2}sh gatbps-echo.sh --help${fR2} for more information
EOF2
        exit 1
      ;;

      #-----------------------------------------------------------------
      # -, --stdin
      #-----------------------------------------------------------------

      - | --stdin)
        x=`cat && echo x` || exit
        x=${x%x}
        x=${x%"$nl"}
        process_operand "$x"
        shift
        continue
      ;;

      --stdin=*)
        cat <<EOF2 >&2
${fr2}gatbps-echo.sh!${fR2} ${fB2}--stdin${fR2} forbids a value
EOF2
        exit 1
      ;;

      #-----------------------------------------------------------------
      # -q, --quote
      #-----------------------------------------------------------------

      -q | --quote)
        quoting_level=`expr $quoting_level + 1` || exit
        shift
        continue
      ;;

      -q*)
        x=-${1#-q}
        shift
        set x -q "$x" "$@"
        shift
        continue
      ;;

      --quote=*)
        cat <<EOF2 >&2
${fr2}gatbps-echo.sh!${fR2} ${fB2}--quote${fR2} forbids a value
EOF2
        exit 1
      ;;

      #-----------------------------------------------------------------
      # unknown option
      #-----------------------------------------------------------------

      *)
        gatbps_unknown_opt "$1"
      ;;

      #-----------------------------------------------------------------

    esac
  fi

  process_operand "$1"

  shift

done

cat <<EOF2 || exit
$output
EOF2

#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#
