#
# This file was generated by GATBPS 0.1.0-5462+g05f081db, which was
# released on 2020-09-07. Before changing it, make sure
# you're doing the right thing. Depending on how GATBPS
# is being used, your changes may be automatically lost.
# A short description of this file follows.
#
# Special file: LTCURRENT.sh
#
# For more information, see the GATBPS manual.
#

#
# With LC_ALL=C, locale-aware programs use the C locale instead of the
# current locale. This is generally the best approach for code that is
# not deliberately designed to work in other locales, as other locales
# may have surprising behavior. The locale affects many programs, like
# awk, grep, sed, and this shell instance itself. For more information,
# see the C standard, the POSIX standard, and the GNU C Library manual.
#

LC_ALL=C
readonly LC_ALL
export LC_ALL

awk=" ${AWK:-awk}"
readonly awk

git=" ${GIT:-git}"
readonly git

sed=" ${SED:-sed}"
readonly sed

uniq=" ${UNIQ:-uniq}"
readonly uniq

file=${1-LTCURRENT}
readonly file

if test -f "$file"; then

  cat <"$file" || exit $?

elif eval "$git"' ls-files --error-unmatch "$0"' >/dev/null 2>&1; then

  xs=`eval "$git"' tag -l "v[0-9]*.[0-9]*.[0-9]*"'` || exit $?

  xs=`eval "$sed"' "s/\\.[^.]*\$//"' <<EOF2
$xs
EOF2
  ` || exit $?

  xs=`eval "$uniq" <<EOF2
$xs
EOF2
  ` || exit $?

  eval "$awk"' "END { print NR - 1 }"' <<EOF2 || exit $?
$xs
EOF2

else

  cat <<EOF2 >&2
LTCURRENT.sh: no LTCURRENT file and no repository
EOF2
  exit 1

fi

exit 0

#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#
