#
# This file was generated by GATBPS 0.1.0-5384+g2e2a4f04, which was
# released on 2019-12-25. Before changing it, make sure
# you're doing the right thing. Depending on how GATBPS
# is being used, your changes may be automatically lost.
# A short description of this file follows.
#
# Special file: VERSION.sh
#
# For more information, see the GATBPS manual.
#

#
# This script (VERSION.sh) helps to create a version string for
# Autotools by using git describe to get the description of HEAD with
# respect to tags that begin with "v" and a digit. Add this script to
# your repository and adjust the following code for your configure.ac
# and Makefile.am files:
#
#   AC_INIT([Example],
#           m4_esyscmd_s([sh VERSION.sh])m4_assert(m4_sysval == 0))
#
#   EXTRA_DIST += $(srcdir)/VERSION
#   EXTRA_DIST += $(srcdir)/VERSION.sh
#
# When running in your repository, the script uses git describe.
# Elsewhere, the script reads the
# VERSION file.
#

#
# With LC_ALL=C, locale-aware programs use the C locale instead of the
# current locale. This is generally the best approach for code that is
# not deliberately designed to work in other locales, as other locales
# may have surprising behavior. The locale affects many programs, like
# awk, grep, sed, and this shell instance itself. For more information,
# see the C standard, the POSIX standard, and the GNU C Library manual.
#

LC_ALL=C
readonly LC_ALL
export LC_ALL

#
# The nl variable holds a newline character. It can be used where a
# literal newline character might be awkward.
#

nl="
"
readonly nl

v_prefix=v

u_prefix=u

if git ls-files --error-unmatch "$0" >/dev/null 2>&1; then

  v_description=`
    git \
      describe \
      --candidates=1 \
      --match="v[0-9]*.[0-9]*.[0-9]*" \
      --tags \
    ;
  `
  s=$?
  readonly v_description

  case $s in
    0)
    ;;
    *)
      cat <<EOF2 >&2
${fr2}VERSION.sh!$fR2 error calculating a $v_prefix* description
${fr2}VERSION.sh!$fR2 did you forget to create/push some tags?
EOF2
      exit 1
    ;;
  esac

  case "${v_description}" in
    *'-'*)
      grep \
        '^v[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}-[0-9]\{1,\}-g[0-9a-f]\{7,\}$' \
        0<<EOF2 \
        1>/dev/null \
      ;
${v_description}
EOF2
      case "${?}" in
        '0')
        ;;
        '1')
          exit 1
        ;;
        *)
          exit 1
        ;;
      esac
    ;;
    *)
      grep \
        '^v[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}$' \
        0<<EOF2 \
        1>/dev/null \
      ;
${v_description}
EOF2
      case "${?}" in
        '0')
        ;;
        '1')
          exit 1
        ;;
        *)
          exit 1
        ;;
      esac
    ;;
  esac
  grep \
    '^v0[0-9]' \
    0<<EOF2 \
    1>/dev/null \
  ;
${v_description}
EOF2
  case "${?}" in
    '0')
      exit 1
    ;;
    '1')
    ;;
    *)
      exit 1
    ;;
  esac
  grep \
    '^v.*[-.]0[0-9]' \
    0<<EOF2 \
    1>/dev/null \
  ;
${v_description}
EOF2
  case "${?}" in
    '0')
      exit 1
    ;;
    '1')
    ;;
    *)
      exit 1
    ;;
  esac
  case "${v_description}" in
    *'-'*)
      u_description=`
        git \
          'describe' \
          '--candidates=1' \
          '--long' \
          '--match=u[0-9]*.[0-9]*.[0-9]*' \
          '--tags' \
        ;
      `
      case "${?}" in
        '0')
        ;;
        *)
          exit 1
        ;;
      esac
      'readonly' 'u_description'
      grep \
        '^u[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}-[0-9]\{1,\}-g[0-9a-f]\{7,\}$' \
        0<<EOF2 \
        1>/dev/null \
      ;
${u_description}
EOF2
      case "${?}" in
        '0')
        ;;
        '1')
          exit 1
        ;;
        *)
          exit 1
        ;;
      esac
      grep \
        '^u0[0-9]' \
        0<<EOF2 \
        1>/dev/null \
      ;
${u_description}
EOF2
      case "${?}" in
        '0')
          exit 1
        ;;
        '1')
        ;;
        *)
          exit 1
        ;;
      esac
      grep \
        '^u.*[-.]0[0-9]' \
        0<<EOF2 \
        1>/dev/null \
      ;
${u_description}
EOF2
      case "${?}" in
        '0')
          exit 1
        ;;
        '1')
        ;;
        *)
          exit 1
        ;;
      esac
      v_tag=`
        git \
          'describe' \
          '--abbrev=0' \
          '--candidates=1' \
          '--match=v[0-9]*.[0-9]*.[0-9]*' \
          '--tags' \
        ;
      `
      case "${?}" in
        '0')
        ;;
        *)
          exit 1
        ;;
      esac
      'readonly' 'v_tag'
      u_tag=`
        git \
          'describe' \
          '--abbrev=0' \
          '--candidates=1' \
          '--match=u[0-9]*.[0-9]*.[0-9]*' \
          '--tags' \
        ;
      `
      case "${?}" in
        '0')
        ;;
        *)
          exit 1
        ;;
      esac
      'readonly' 'u_tag'
      git \
        'merge-base' \
        '--is-ancestor' \
        "${v_tag}" \
        "${u_tag}" \
      ;
      case "${?}" in
        '0')
        ;;
        '1')
          exit 1
        ;;
        *)
          exit 1
        ;;
      esac
      sed '
        s/^u//
        s/-g/+g/
      ' 0<<EOF2
${u_description}
EOF2
      case "${?}" in
        '0')
        ;;
        *)
          exit 1
        ;;
      esac
    ;;
    *)
      sed '
        s/^v//
      ' 0<<EOF2
${v_description}
EOF2
      case "${?}" in
        '0')
        ;;
        *)
          exit 1
        ;;
      esac
    ;;
  esac

elif test -f VERSION; then

  version=`cat VERSION`
  s=$?
  readonly version

  case $s in
    0)
    ;;
    *)
      exit $s
    ;;
  esac

  case $version in
    0.0.0-0+g0000000)
      cat <<EOF2 >&2
${fy2}VERSION.sh:$fR2 no repository and VERSION says 0.0.0-0+g0000000
${fy2}VERSION.sh:$fR2 are you working with a source archive?
${fy2}VERSION.sh:$fR2 that's generally not a good idea
EOF2
    ;;
  esac

else
  echo 'VERSION.sh: not in repository and VERSION not found' >&2
  exit 1
fi

#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#
