\input texinfo
@setfilename gatbps.info

@ifclear insertascii
@documentencoding UTF-8
@end ifclear

@documentlanguage en

@include PACKAGEVERSION.texi

@settitle GATBPS @value{PACKAGEVERSION} Manual

@include AWKDEFAULTTEXI.texi
@include CC0-1.0-copying.texi
@include PACKAGEDATE.texi
@include SEDDEFAULTTEXI.texi
@include TEXIANYDEFAULTTEXI.texi
@include math.texi

@set fullmanual

@defindex sf
@defindex tm

@dircategory Individual utilities
@direntry
* gatbps: (gatbps)Invoking gatbps.              Generate basic package files.
@end direntry

@dircategory Software development
@direntry
* GATBPS: (gatbps).             Generate basic package files.
@end direntry

@ifplaintext
@chapheading GATBPS@tie{}@w{@value{PACKAGEVERSION}} Manual
@end ifplaintext

@titlepage
@title GATBPS@tie{}@w{@value{PACKAGEVERSION}} Manual
@subtitle @w{@value{PACKAGEDATE}}
@vskip 0pt plus 1filll
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@include bothcontents.texi

@ifnottex
@node Top
@top GATBPS@tie{}@w{@value{PACKAGEVERSION}} Manual

This manual is for
GATBPS@tie{}@w{@value{PACKAGEVERSION}},
which was released
on@tie{}@w{@value{PACKAGEDATE}}@.
@ifplaintext

@insertcopying
@end ifplaintext

@menu
* Copyright Information::
* Introduction::
* Building and Installation::
* Invoking @w{@t{gatbps}}::
* Plain Files::
* Copyright Texts::
* Writing Mathematical Notation in Texinfo::
* Timestamp Preservation during Autoconf Instantiation::
* Using the Autotools to Process M4::
* Checking for Missing Autoconf Macros::
* Formatting Autoconf Files::
* Formatting Automake Files::
* Using the Autotools to Compile Java::
* Using the Autotools to Generate Javadoc::
* Cloning Git Repositories with the Autotools::
* Using the Autotools to Create Git Archives::
* Using the Autotools to Build Docker Images::
* Invoking @w{@t{awk-form-sh}}::
* Invoking @w{@t{sh-form-sh}}::
* Invoking @w{@t{texi-form-sh}}::
* Invoking @w{@t{troff-form-sh}}::
* Special File Reference::
* Release Notes::
* Creative Commons Zero@tie{}@w{1-0}::
* Concept Index::
* Special File Index::
* Texinfo Macro Index::
@end menu
@end ifnottex

@include gatbps/Copyright-Information.texi

@include gatbps/Introduction.texi

@include gatbps/Building-and-Installation.texi

@include gatbps/Invoking-gatbps.texi

@include gatbps/Plain-Files.texi

@include gatbps/Copyright-Texts.texi

@include gatbps/Writing-Mathematical-Notation-in-Texinfo.texi

@include gatbps/Timestamp-Preservation-during-Autoconf-Instantiation.texi

@include gatbps/Using-the-Autotools-to-Process-M4.texi

@include gatbps/Checking-for-Missing-Autoconf-Macros.texi

@include gatbps/Formatting-Autoconf-Files.texi

@include gatbps/Formatting-Automake-Files.texi

@include gatbps/Using-the-Autotools-to-Compile-Java.texi

@include gatbps/Using-the-Autotools-to-Generate-Javadoc.texi

@include gatbps/Cloning-Git-Repositories-with-the-Autotools.texi

@include gatbps/Using-the-Autotools-to-Create-Git-Archives.texi

@include gatbps/Using-the-Autotools-to-Build-Docker-Images.texi

@include gatbps/Invoking-awk-form-sh.texi

@include gatbps/Invoking-sh-form-sh.texi

@include gatbps/Invoking-texi-form-sh.texi

@include gatbps/Invoking-troff-form-sh.texi

@include gatbps/Special-File-Reference.texi

@include gatbps/Release-Notes.texi

@include CC0-1.0-appendix.texi

@node Concept Index
@unnumbered Concept Index

@printindex cp

@node Special File Index
@unnumbered Special File Index

@printindex sf

@node Texinfo Macro Index
@unnumbered Texinfo Macro Index

@printindex tm
@ifxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifxml
@bye
