"
" This file was generated by GATBPS 0.0.0-1883-g724685b, which was
" released on 2015-12-29. Before changing it, make sure
" you're doing the right thing. Depending on how GATBPS
" is being used, your changes may be automatically lost.
" A short description of this file follows.
"
" Special file: Makefile.am.vim
"
" For more information, see the GATBPS manual.
"
:%sm/^## begin_variables$/&\r/
:%sm/^## end_variables$/\r&/
:/^## begin_variables$/+1,/^## end_variables$/-1g/./s/$/\b/
:/^## begin_variables$/+1,/^## end_variables$/-2g/^\n./.+1,/^$/-1j!
:/^## begin_variables$/+1,/^## end_variables$/-1g/^$/d
:/^## begin_variables$/+1,/^## end_variables$/-1sort
:/^## begin_variables$/+1,/^## end_variables$/-1s/\b/\r/g
:%sm/^## begin_variables$/&\r/
:/^## begin_variables$/+1,/^## end_variables$/-1g/+=/.,/^$/-1sort u
:%sm/^## begin_rules$/&\r/
:%sm/^## end_rules$/\r&/
:/^## begin_rules$/+1,/^## end_rules$/-1g/./s/$/\b/
:/^## begin_rules$/+1,/^## end_rules$/-2g/^\n./.+1,/^$/-1j!
:/^## begin_rules$/+1,/^## end_rules$/-1g/^$/d
:/^## begin_rules$/+1,/^## end_rules$/-1sort
:/^## begin_rules$/+1,/^## end_rules$/-1s/\b/\r/g
:%sm/^## begin_rules$/&\r/
:/^## begin_rules$/+1,/^## end_rules$/-2g/^$/.+1,/^\($\|\t\)/-1sort u
"
" The authors of this file have waived all copyright and
" related or neighboring rights to the extent permitted by
" law as described by the CC0 1.0 Universal Public Domain
" Dedication. You should have received a copy of the full
" dedication along with this file, typically as a file
" named <CC0-1.0.txt>. If not, it may be available at
" <https://creativecommons.org/publicdomain/zero/1.0/>.
"
