//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

[#acl_GATBPS_PUSH_VAR]
= The `GATBPS_PUSH_VAR` macro

.Autoconf
[source,subs="{subs_source}"]
----
include::acl_include_gatbps_ac_fragment.adoc[]

{acl_GATBPS_PUSH_VAR}(<name>, <value>)
----

The `{acl_GATBPS_PUSH_VAR}` macro saves the current value of the shell
variable `<name>` onto a stack and updates `<name>` to `<value>`.
The most recent saved value of `<name>` can later be restored or
discarded by calling the `{acl_GATBPS_POP_VAR}` or
`{acl_GATBPS_KEEP_VAR}` macros.

If `<name>` was unset, its unset-ness is saved onto the stack, not an
empty value.
In this case, restoring the saved value will unset `<name>`, not set it
to an empty value.

Each `<name>` gets its own stack.

//
