//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

[[acl_GATBPS_CHECK]]
= The `GATBPS_CHECK` macro

.Autoconf
[source,subs="{subs_source}"]
----
include::acl_include_gatbps_ac_fragment.adoc[]

{acl_GATBPS_CHECK}(
  <message>,
  <name>,
  <<code>>,
  <precondition>?,
  <skip_value=no>?)
----

The `{acl_GATBPS_CHECK}` macro extends the `{acl_AC_CACHE_CHECK}` macro
as follows:

* The cache variable is named `gatbps_cv_<name>`.

* {empty}
`<name>` is set to `$gatbps_cv_<name>` after `{acl_AC_CACHE_CHECK}`
completes.

* {empty}
`<name>_was_cached` is set to `1` or `0` to indicate whether `<name>`
was cached.

* {empty}
`<name>_was_cached_sh` is set to `:` or `false` corresponding to
`<name>_was_cached`.

* `{acl_AC_SUBST}` is called for `<name>`.

* The end of `<name>` may include zero or more specifiers, each of which
consists of a `:` character followed by an identifier.
These specifiers are removed from `<name>` when forming variable names.

* If `:notmake` is specified at the end of `<name>`, then
`{aml_AM_SUBST_NOTMAKE}` is called for `<name>`.

* {empty}
If `:notbool` is specified at the end of `<name>`, then boolean
detection is disabled.
Otherwise, boolean detection is enabled, in which case all of the
following occur:

** {empty}
If `gatbps_cv_<name>` is set to `yes`, `no`, `yes (guess)`, or
`no (guess)`, then all of the following occur:

*** {empty}
`<name>` is adjusted to `1` if it is `yes` or `yes (guess)`, or to `0`
if it is `no` or `no (guess)`.

*** {empty}
`<name>_sh` is set to `:` or `false` to indicate whether `$<name>` is
`1` or `0`.

*** {empty}
`<name>_is_guess` is set to `1` or `0` to indicate whether `$<name>`
originally ended in `(guess)`.

*** {empty}
`<name>_is_guess_sh` is set to `:` or `false` to indicate whether
`$<name>_is_guess` is `1` or `0`.

*** `{acl_AC_DEFINE}` is called for `<name>`.

** {empty}
If `gatbps_cv_<name>` is not set to `yes`, `no`, `yes (guess)`, or
`no (guess)`, then `<name>_sh` is set to `false`.

** `{aml_AM_CONDITIONAL}` is called for `<name>` using `$<name>_sh`.

* If `:bool` is specified at the end of `<name>`, then the `:notbool`
specifier is ignored and boolean behavior is enforced: an error will
occur if `gatbps_cv_<name>` is not set to `yes` or `no`.

* If `<precondition>` is given, it will be interpreted as a boolean
expression.
If the result of the expression is false, `gatbps_cv_<name>` will be set
to `<skip_value>` instead of executing `<<code>>` to set it.
The expression may use variable names, literal ``1```'s, ``0```'s,
``yes```'s, and ``no```'s, the `!`, `&&`, and `||` operators,
parentheses for precedence, and space, tab, and newline characters for
separation.
Each variable should be set to `1`, `0`, `yes`, or `no`.

//
