//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

[[acl_GATBPS_SQUISH]]
= The `GATBPS_SQUISH` macro

.Autoconf
[source,subs="{subs_source}"]
----
include::acl_include_gatbps_ac_fragment.adoc[]

{acl_GATBPS_SQUISH}(
  <text>)
----

The `{acl_GATBPS_SQUISH}` macro expands to `[<text>]` with the following
adjustments performed, in order:

. {empty}
Each maximal sequence of characters in `<text>` that contains only
newline, tab, or space characters is replaced with a single space
character.

. {empty}
If the result of the previous step begins with a space character, that
character is deleted.

. {empty}
If the result of the previous step ends with a space character, that
character is deleted.

//
