//
// The authors of this file have waived all copyright and
// related or neighboring rights to the extent permitted by
// law as described by the CC0 1.0 Universal Public Domain
// Dedication. You should have received a copy of the full
// dedication along with this file, typically as a file
// named <CC0-1.0.txt>. If not, it may be available at
// <https://creativecommons.org/publicdomain/zero/1.0/>.
//

[[aml_temporary_files]]
= Temporary files

Every recipe generated by GATBPS uses `$@$(TMPEXT).tmp*` as the naming
pattern for any temporary files and directories that may be created
during the process of building `$@`.
GATBPS also defines `TSUF = $(TMPEXT).tmp` to simplify the use of the
naming pattern.
For example, a recipe that needs to create two temporary files could
name them `$@$(TSUF)1` and `$@$(TSUF)2`.

GATBPS itself does not define `TMPEXT`, but the user may do so to add
extra suffixes for other purposes.
For example, the user could define `TMPEXT = .gitignorable` and add
`*.gitignorable.*` to their `.gitignore` file to ensure that all
temporary files and directories are ignored by Git.
Note that `TSUF` will be `.tmp` if the user leaves `TMPEXT` undefined,
which is a reasonable default.

////
./ is included for
extra protection against catastrophic deletions like rm -f -r /
////

----
foo:
	echo bar >$@$(TSUF)1
	echo baz >$@$(TSUF)2
	cat $@$(TSUF)1 $@$(TSUF)2 >$@$(TSUF)3
	mv -f $@$(TSUF)3 $@

foo/clean: FORCE
	-rm -f -r ./$(@D) ./$(@D)$(TSUF)*

mostlyclean-local: foo/clean
----

//
