@ifset fullmanual
@node Building and Installation
@chapter Building and Installation
@end ifset
@ifclear fullmanual
@unnumbered Building and Installation
@end ifclear

@noindent
GATBPS uses the GNU Autotools for building and installation@.

@include indent.texi
The Info directory entries for the manual follow the standard formatting
conventions, which include starting program descriptions on the 49th
column and other descriptions on the 33rd column@.
However, installation reformats the entries by default, which may move
some of the program descriptions to the 33rd column@.
This can be prevented by setting the
@w{@t{INSTALL_INFO_NO_INDENT}}
environment variable to any value during the
@w{@t{make@w{ }install}}
command@.
For example, the following command might be used:

@example
sudo@w{ }INSTALL_INFO_NO_INDENT=yes@w{ }make@w{ }install
@end example
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
