@ifset fullmanual
@node Building and Installation
@chapter Building and Installation
@end ifset
@ifclear fullmanual
@unnumbered Building and Installation
@end ifclear

@noindent
GATBPS uses the GNU Build System for building and installation@.
The details are slightly different depending on whether you are working
with the Git repository, a tree archive, or a distribution archive@.
If you are unsure of which one you are working with, then you can
distinguish them as follows:

@enumerate
@item
If there is a subdirectory named
@w{@t{.@:git}}
in the directory that contains the
@w{@t{configure.@:ac}}
file, then you are working with the Git repository@.

@item
Otherwise, if there is a subdirectory named
@w{@t{dev-aux}}
in the directory that contains the
@w{@t{configure.@:ac}}
file, then you are working with a tree archive@.

@item
Otherwise, you are working with a distribution archive@.
@end enumerate

@include indent.texi
If you are working with the Git repository or a tree archive, then the
first step is to initialize the build system@.
If you are working with a distribution archive, then you should skip
this step, as the build system is already initialized@.
To initialize the build system, run the following command after making
sure that you have the GNU Autotools installed:

@example
autoreconf@w{ }-@w{-}install
@end example

@include indent.texi
The Info directory entries for the manual follow the standard formatting
conventions, which include starting program descriptions on the 49th
column and other descriptions on the 33rd column@.
However, installation reformats the entries by default, which may move
some of the program descriptions to the 33rd column@.
This can be prevented by setting the
@w{@t{INSTALL_INFO_NO_INDENT}}
environment variable to any value during the
@w{@t{make@w{ }install}}
command@.
For example, the following command might be used:

@example
sudo@w{ }INSTALL_INFO_NO_INDENT=yes@w{ }make@w{ }install
@end example

@menu
* Package Formats::
* Build System Initialization::
* Required Packages::
* Configuration::
* Building::
* Installation::
@end menu

@lowersections
@include Package-Formats.texi

@include Build-System-Initialization.texi

@include Required-Packages.texi

@include Configuration.texi

@include Building.texi

@include Installation.texi
@raisesections
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
