@node Formatting Automake Variable Sections
@chapter Formatting Automake Variable Sections

@cindex Automake variable section
@cindex variable section, Automake
@noindent
A sequence of zero or more lines of text that is immediately preceded by
a line containing exactly
``@w{@t{## begin_variables}}'',
that is immediately followed by a line containing exactly
``@w{@t{## end_variables}}'',
that does not contain any lines beginning with
``@w{@t{## begin_}}''
or
``@w{@t{## end_}}'',
and that does not contain any backspace control characters is called an
@i{Automake variable section}@.
If the last line of an Automake variable section ends with a
``@w{@t{\}}''@tie{}character,
then an empty line is implicitly added to the end of the variable
section@.
Each maximal contiguous subsequence of lines that consists of a line not
ending with a
``@w{@t{\}}''@tie{}character
along with all immediately preceding lines ending with
``@w{@t{\}}''@tie{}characters
is called a
@i{logical line}@.
The original lines are often called
@i{physical lines}
to avoid confusion with logical lines@.
A logical line that contains exactly an empty physical line is called a
@i{paragraph separator}@.
Each maximal contiguous subsequence of one or more logical lines that
does not contain a paragraph separator is called a
@i{variable paragraph}@.

@example
## begin_variables

bin_PROGRAMS =
# A comment block can go here.
## Automake comments are okay too.
bin_PROGRAMS += hello

hello_SOURCES =
hello_SOURCES += \
  hello.c

## end_variables
@end example
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
