@node Formatting Automake Variable Sections
@chapter Formatting Automake Variable Sections

@cindex Automake variable section
@cindex variable section, Automake
@noindent
A sequence of zero or more lines of text that is immediately preceded by
a line containing exactly
``@w{@t{## begin_variables}}'',
that is immediately followed by a line containing exactly
``@w{@t{## end_variables}}'',
and that does not contain any lines beginning with
``@w{@t{## begin_}}''
or
``@w{@t{## end_}}''
is called an
@i{Automake variable section}@.
If the last physical line ends with a
`@w{@t{\}}'@tie{}character,
then a blank physical line is implicitly appended@.
Each maximal contiguous subsequence of physical lines that consists of a
line not ending with a
`@w{@t{\}}'@tie{}character
along with any immediately preceding physical lines ending with
`@w{@t{\}}'@tie{}characters
is called a
@i{logical line}@.
To reduce confusion, the original lines are sometimes called
@i{physical lines}@.
Each maximal contiguous subsequence of logical lines that does not
contain a logical line containing solely a physical blank line is called
a
@i{variable paragraph}@.

@example
## begin_variables

foo =
# A comment block can go here.
## Automake comments are okay too.
foo += bar
foo += baz

## end_variables
@end example

@example
foo +=
# A comment block can go here.
## Automake comments are okay too.
foo += bar
foo += baz
@end example
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
