@node @t{gatbps} Options
@chapter @t{gatbps} Options

Each option has
one or more names, and each
name is either long or short@.
Each long name consists of two
hyphen-minus characters followed by
zero or more printable characters except
for the space and equals sign characters,
and each short name consists of one hyphen-minus
character followed by one printable character
except for the space and hyphen-minus characters@.
Each option either requires a value,
permits a value, or forbids a value@.

Let
@w{@t{-@w{-}}@i{L}}
and
@w{@t{-}@i{S}}
be long and short names for an option and
@w{@i{V}}
be a value@.
If the option
requires a value,
then it may be written as either
@w{@t{-@w{-}}@i{L}@t{=}@i{V}@comma{}}
@w{@t{-@w{-}}@i{L@w{ }V}@comma{}}
@w{@t{-}@i{SV}@comma{}}
or
@w{@t{-}@i{S@w{ }V}@.}
If the option
permits a value,
then it may be written as either
@w{@t{-@w{-}}@i{L}@t{=}@i{V}@comma{}}
@w{@t{-@w{-}}@i{L}@comma{}}
@w{@t{-}@i{SV}@comma{}}
or
@w{@t{-}@i{S}@.}
If the option
forbids a value,
then it may be written as either
@w{@t{-@w{-}}@i{L}}
or
@w{@t{-}@i{S}@comma{}}
and in the latter case
it may be combined with an
immediately following argument in
(combined) short form by deleting the
@w{@t{-}@i{S}}
argument and inserting the
@w{@i{S}}
character into the following
argument just after the leading
@w{@t{-}}
character@.

The following options are supported:

@table @asis
@item @w{@t{-@w{-}}}
@include ipez.texi
The
@w{@t{-@w{-}}}
option disables option detection,
causing all remaining arguments
to be interpreted as operands@.

@item @w{@t{-@w{-}all}[@t{=}@i{V}]}
@itemx @w{@t{-a}[@i{V}]}
@include ipez.texi
The
@w{@t{-@w{-}all}}
option prepends
all special files to
the remaining arguments@.
Each is prefixed with
@w{@i{V}@.}
If
@w{@i{V}}
is not empty and does not
end with a slash character,
then one is appended@.
If
@w{@i{V}}
is omitted, then it
is taken to be empty@.

@item @w{@t{-@w{-}help}[@t{=}@i{V}]}
@include ipez.texi
The
@w{@t{-@w{-}help}}
option writes text to standard output and
causes all remaining arguments to be ignored@.
If
@w{@i{V}}
is omitted, then
the text is a short description of the program@.
Otherwise, the text is a short description
of the file that would be generated by the
@w{@t{gatbps@w{ }-@w{-}@w{ }}@i{V}}
command@.

@item @w{@t{-@w{-}man}}
@include ipez.texi
The
@w{@t{-@w{-}man}}
option writes text to standard output and
causes all remaining arguments to be ignored@.
The text is the source code
of the program's manual page,
which can be viewed with any
command that is analogous to the
@w{@t{tbl@w{ }|@w{ }nroff@w{ }-man}}
command@.
In particular, the
@w{@t{man@w{ }-l@w{ }-}}
command can be used on
most GNU/Linux systems@.

@item @w{@t{-@w{-}recursive}}
@itemx @w{@t{-r}}
@include ipez.texi
The
@w{@t{-@w{-}recursive}}
option enables
the recursion phase
of operand processing@.
For more information,
@pxref{@t{gatbps} Operands}@.

@item @w{@t{-@w{-}style}[@t{=}@i{V}]}
@include ipez.texi
The
@w{@t{-@w{-}style}}
option prepends an instance of the
@w{@t{-@w{-}style-stderr}}
option and an instance of the
@w{@t{-@w{-}style-stdout}}
option to the remaining arguments@.
If
@w{@i{V}}
is omitted, then neither
instance is given a value@.
Otherwise, both are given the value
@w{@i{V}@.}

@item @w{@t{-@w{-}style-stderr}[@t{=}@i{V}]}
@include ipez.texi
The
@w{@t{-@w{-}style-stderr}}
option enables or disables bold,
underline, and color styling of
text written to standard error,
which is initially disabled@.
If
@w{@i{V}}
is
@w{@t{always}@comma{}}
then styling is enabled@.
If
@w{@i{V}}
is
@w{@t{never}@comma{}}
then styling is disabled@.
If
@w{@i{V}}
is
@w{@t{auto}@comma{}}
then styling is enabled
if standard error is associated
with a terminal or disabled if not@.
Any other value causes an error@.
If
@w{@i{V}}
is omitted, then it is taken to be
@w{@t{always}@.}

@item @w{@t{-@w{-}style-stdout}[@t{=}@i{V}]}
@include ipez.texi
The
@w{@t{-@w{-}style-stdout}}
option enables or disables bold,
underline, and color styling of
text written to standard output,
which is initially disabled@.
If
@w{@i{V}}
is
@w{@t{always}@comma{}}
then styling is enabled@.
If
@w{@i{V}}
is
@w{@t{never}@comma{}}
then styling is disabled@.
If
@w{@i{V}}
is
@w{@t{auto}@comma{}}
then styling is enabled
if standard output is associated
with a terminal or disabled if not@.
Any other value causes an error@.
If
@w{@i{V}}
is omitted, then it is taken to be
@w{@t{always}@.}

@item @w{@t{-@w{-}version}}
@include ipez.texi
The
@w{@t{-@w{-}version}}
option writes text to standard output and
causes all remaining arguments to be ignored@.
The text is the program's
name, package, version number,
release date, and copyright information@.
@end table
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
