@node @w{@t{gatbps}} Options
@chapter @w{@t{gatbps}} Options

@noindent
Each option has one or more names, and each name is either long or
short@.
Each long name consists of two
@w{@t{-}}
characters followed by zero or more characters except the
@w{@t{=}}
character, and each short name consists of one
@w{@t{-}}
character followed by one character except the
@w{@t{-}}
character@.
Each option either requires, permits, or forbids a value@.

@include indent.texi
Let
@w{@t{-@w{-}}@i{L}}
and
@w{@t{-}@i{S}}
be long and short names for an option and
@w{@i{V}}
be a value@.
If the option requires a value, then it may be written as either
@w{@t{-@w{-}}@i{L}@t{=}@i{V}},
@w{@t{-@w{-}}@i{L V}},
@w{@t{-}@i{SV}},
or
@w{@t{-}@i{S V}@.}
If the option permits a value, then it may be written as either
@w{@t{-@w{-}}@i{L}@t{=}@i{V}},
@w{@t{-@w{-}}@i{L}},
@w{@t{-}@i{SV}},
or
@w{@t{-}@i{S}@.}
If the option forbids a value, then it may be written as either
@w{@t{-@w{-}}@i{L}}
or
@w{@t{-}@i{S}},
and in the latter case it may be combined with an immediately following
option or combination of options by deleting the
@w{@t{-}@i{S}}
argument and inserting the
@w{@i{S}}
character into the following argument just after the leading
@w{@t{-}}
character@.
For example,
@w{@t{-}@i{S }@t{-}@i{K}}
and
@w{@t{-}@i{S }@t{-@w{-}}@i{K}}
may be written as
@w{@t{-}@i{SK}}
and
@w{@t{-}@i{S}@t{-}@i{K}},
respectively@.

@include indent.texi
The following options are supported:

@table @asis
@item @w{@t{-@w{-}}}
@include ipez.texi
The
@w{@t{-@w{-}}}
option disables option detection, causing all remaining arguments to be
interpreted as operands@.

@item @w{@t{-@w{-}all}[@t{=}@i{V}]}
@itemx @w{@t{-a}[@i{V}]}
@include ipez.texi
The
@w{@t{-@w{-}all}[@t{=}@i{V}]}
option inserts the names of all special files in front of the remaining
arguments@.
Each name is prefixed with
@w{@i{V}@.}
If
@w{@i{V}}
is omitted, then it is taken to be empty@.
If
@w{@i{V}}
is not empty and does not end with a slash character, then a slash
character is appended to
@w{@i{V}@.}
If
@w{@i{V}}
begins with a hyphen-minus character, then a period character and a
slash character are prepended to
@w{@i{V}@.}
Note that no special file name begins with a hyphen-minus character@.

@item @w{@t{-@w{-}awk=}@i{V}}
@include ipez.texi
The
@w{@t{-@w{-}awk=}@i{V}}
option sets the command name
that will be used to invoke the
@w{@t{awk}}
program to
@w{@i{V}@.}
If
@w{@i{V}}
is
@w{@t{auto}},
then the command name is inferred@.
The copy of the
program that corresponds
to this copy of the manual
behaves as if an instance of the
@w{@t{-@w{-}awk=@value{AWKDEFAULTTEXI}}}
option were added to the
arguments at a position that
lies before all original arguments
and before any argument added by the
@w{@t{AWK}}
environment variable@.
Other copies may use other initial values@.

@item @w{@t{-@w{-}boundary}}
@itemx @w{@t{-b}}
@include ipez.texi
The
@w{@t{-@w{-}boundary}}
option enables recursion
for the next operand but
not for its prerequisites@.

@item @w{@t{-@w{-}dry-run}}
@itemx @w{@t{-n}}
@include ipez.texi
The
@w{@t{-@w{-}dry-run}}
option enables printing and disables generation@.

@item @w{@t{-@w{-}help}[@t{=}@i{V}]}
@include ipez.texi
The
@w{@t{-@w{-}help}[@t{=}@i{V}]}
option writes text to standard output and
causes all remaining arguments to be ignored@.
If
@w{@i{V}}
is omitted, then
the text is a short description of the program@.
Otherwise, the text is a short description
of the file that would be generated by the
@w{@t{gatbps -@w{-} }@i{V}}
command@.

@item @w{@t{-@w{-}man}}
@include ipez.texi
The
@w{@t{-@w{-}man}}
option writes text to standard output and
causes all remaining arguments to be ignored@.
The text is the source code
of the program's manual page,
which can be processed with any
command that is analogous to the
@w{@t{tbl | nroff -man}}
command@.
In particular, the
@w{@t{man -l -}}
command can be used on most systems@.

@item @w{@t{-@w{-}no-dry-run}}
@itemx @w{@t{-N}}
@include ipez.texi
The
@w{@t{-@w{-}no-dry-run}}
option disables printing and enables generation@.
However, printing remains enabled if the
@w{@t{-@w{-}verbose}}
option is in effect@.

@item @w{@t{-@w{-}no-recursive}}
@itemx @w{@t{-R}}
@include ipez.texi
The
@w{@t{-@w{-}no-recursive}}
option disables recursion@.
However, this does not affect the
@w{@t{-@w{-}boundary}}
option@.

@item @w{@t{-@w{-}no-verbose}}
@itemx @w{@t{-V}}
@include ipez.texi
The
@w{@t{-@w{-}no-verbose}}
option disables printing@.
However, printing remains enabled if the
@w{@t{-@w{-}dry-run}}
option is in effect@.

@item @w{@t{-@w{-}recursive}}
@itemx @w{@t{-r}}
@include ipez.texi
The
@w{@t{-@w{-}recursive}}
option enables recursion@.

@item @w{@t{-@w{-}sed=}@i{V}}
@include ipez.texi
The
@w{@t{-@w{-}sed=}@i{V}}
option sets the command name
that will be used to invoke the
@w{@t{sed}}
program to
@w{@i{V}@.}
If
@w{@i{V}}
is
@w{@t{auto}},
then the command name is inferred@.
The copy of the
program that corresponds
to this copy of the manual
behaves as if an instance of the
@w{@t{-@w{-}sed=@value{SEDDEFAULTTEXI}}}
option were added to the
arguments at a position that
lies before all original arguments
and before any argument added by the
@w{@t{SED}}
environment variable@.
Other copies may use other initial values@.

@item @w{@t{-@w{-}style}[@t{=}@i{V}]}
@include ipez.texi
The
@w{@t{-@w{-}style}[@t{=}@i{V}]}
option prepends an instance of the
@w{@t{-@w{-}style-stderr}}
option and an instance of the
@w{@t{-@w{-}style-stdout}}
option to the remaining arguments@.
If
@w{@i{V}}
is omitted, then neither
instance is given a value@.
Otherwise, both are given the value
@w{@i{V}@.}

@item @w{@t{-@w{-}style-stderr}[@t{=}@i{V}]}
@include ipez.texi
The
@w{@t{-@w{-}style-stderr}[@t{=}@i{V}]}
option enables or disables bold,
underline, and color styling of
text written to standard error,
which is initially disabled@.
If
@w{@i{V}}
is omitted, then it is taken to be
@w{@t{always}@.}
If
@w{@i{V}}
is
@w{@t{always}},
then styling is enabled@.
If
@w{@i{V}}
is
@w{@t{never}},
then styling is disabled@.
If
@w{@i{V}}
is
@w{@t{auto}},
then styling is enabled
if standard error is associated
with a terminal or disabled if not@.
Any other value causes an error@.

@item @w{@t{-@w{-}style-stdout}[@t{=}@i{V}]}
@include ipez.texi
The
@w{@t{-@w{-}style-stdout}[@t{=}@i{V}]}
option enables or disables bold,
underline, and color styling of
text written to standard output,
which is initially disabled@.
If
@w{@i{V}}
is omitted, then it is taken to be
@w{@t{always}@.}
If
@w{@i{V}}
is
@w{@t{always}},
then styling is enabled@.
If
@w{@i{V}}
is
@w{@t{never}},
then styling is disabled@.
If
@w{@i{V}}
is
@w{@t{auto}},
then styling is enabled
if standard output is associated
with a terminal or disabled if not@.
Any other value causes an error@.

@item @w{@t{-@w{-}texi2any=}@i{V}}
@include ipez.texi
The
@w{@t{-@w{-}texi2any=}@i{V}}
option sets the command name
that will be used to invoke the
@w{@t{texi2any}}
program to
@w{@i{V}@.}
If
@w{@i{V}}
is
@w{@t{auto}},
then the command name is inferred@.
The copy of the
program that corresponds
to this copy of the manual
behaves as if an instance of the
@w{@t{-@w{-}texi2any=@value{TEXIANYDEFAULTTEXI}}}
option were added to the
arguments at a position that
lies before all original arguments
and before any argument added by the
@w{@t{TEXI2ANY}}
environment variable@.
Other copies may use other initial values@.

@item @w{@t{-@w{-}verbose}}
@itemx @w{@t{-v}}
@include ipez.texi
The
@w{@t{-@w{-}verbose}}
option enables printing@.

@item @w{@t{-@w{-}version}}
@include ipez.texi
The
@w{@t{-@w{-}version}}
option writes text to standard output and
causes all remaining arguments to be ignored@.
The text is the program's
name, package, version number,
release date, and copyright information@.
@end table
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
