@node @t{gatbps} Environment Variables
@chapter @t{gatbps} Environment Variables

The following environment variables are supported:

@table @asis
@item @w{@t{AWK}}
@include ipez.texi
If the
@w{@t{AWK}}
environment variable
is set to a nonempty value
@w{@i{V}@comma{}}
then an instance of the
@w{@t{-@w{-}awk=}@i{V}}
option is added to the
arguments at a position that
lies before all original arguments@.
Otherwise, the
@w{@t{AWK}}
environment variable has no effect@.

@item @w{@t{SED}}
@include ipez.texi
If the
@w{@t{SED}}
environment variable
is set to a nonempty value
@w{@i{V}@comma{}}
then an instance of the
@w{@t{-@w{-}sed=}@i{V}}
option is added to the
arguments at a position that
lies before all original arguments@.
Otherwise, the
@w{@t{SED}}
environment variable has no effect@.

@item @w{@t{STYLE}}
@include ipez.texi
If the
@w{@t{STYLE}}
environment variable
is set to a nonempty value
@w{@i{V}@comma{}}
then an instance of the
@w{@t{-@w{-}style=}@i{V}}
option is added to the
arguments at a position that
lies before all original arguments
and before any arguments added by the
@w{@t{STYLE_STDERR}}
and
@w{@t{STYLE_STDOUT}}
environment variables@.
Otherwise, the
@w{@t{STYLE}}
environment variable has no effect@.

@item @w{@t{STYLE_STDERR}}
@include ipez.texi
If the
@w{@t{STYLE_STDERR}}
environment variable
is set to a nonempty value
@w{@i{V}@comma{}}
then an instance of the
@w{@t{-@w{-}style-stderr=}@i{V}}
option is added to the
arguments at a position that
lies before all original arguments
and after any argument added by the
@w{@t{STYLE}}
environment variable@.
Otherwise, the
@w{@t{STYLE_STDERR}}
environment variable has no effect@.

@item @w{@t{STYLE_STDOUT}}
@include ipez.texi
If the
@w{@t{STYLE_STDOUT}}
environment variable
is set to a nonempty value
@w{@i{V}@comma{}}
then an instance of the
@w{@t{-@w{-}style-stdout=}@i{V}}
option is added to the
arguments at a position that
lies before all original arguments
and after any argument added by the
@w{@t{STYLE}}
environment variable@.
Otherwise, the
@w{@t{STYLE_STDOUT}}
environment variable has no effect@.

@item @w{@t{TEXI2ANY}}
@include ipez.texi
If the
@w{@t{TEXI2ANY}}
environment variable
is set to a nonempty value
@w{@i{V}@comma{}}
then an instance of the
@w{@t{-@w{-}texi2any=}@i{V}}
option is added to the
arguments at a position that
lies before all original arguments@.
Otherwise, the
@w{@t{TEXI2ANY}}
environment variable has no effect@.
@end table
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
