@node @w{@t{gatbps}} Output Files
@chapter @w{@t{gatbps}} Output Files

@noindent
For each
operand@tie{}@w{@i{X}}
for which generation is enabled
(@pxref{@w{@t{gatbps}} Operands}),
the output
file@tie{}@w{@i{X}}
is attempted to be generated, and the ten files
@w{@i{X}@t{.@:tmp0}}
to@tie{}@w{@i{X}@t{.@:tmp9}}
are reserved for temporary use during this process@.
Generation begins by attempting to delete the temporary files with
individual
@w{@t{rm -f}}
commands@.
If any of these commands fails, then generation ends@.
Otherwise, the output file is attempted to be generated@.
If this fails, then the state of the output file is unspecified@.
Regardless of whether this fails, generation ends by attempting to
delete the temporary files again@.
If the program is terminated by a signal during generation, then the
state of the output file and the temporary files is unspecified@.
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
