@node Introduction
@chapter Introduction

@noindent
GATBPS (pronunciation: gat-bee-pee-ESS) is a software package for
generating basic files for software packages@.
It was originally created to provide a
small number of shell scripts to be used with the
GNU Autotools, and its name was an abbreviation for
GNU Autotools Boilerplate Scripts@.
However, it quickly grew to provide other
kinds of basic files, and its name is now
considered to be an abbreviation for
Generate Basic Package Stuff@.
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
