@node Invoking @t{gatbps}
@chapter Invoking @t{gatbps}

This section describes
@w{@t{gatbps}}
in the same way as its manual page@.

@menu
* @t{gatbps} Synopsis::
* @t{gatbps} Description::
* @t{gatbps} Options::
* @t{gatbps} Operands::
* @t{gatbps} Standard Input::
* @t{gatbps} Input Files::
* @t{gatbps} Environment Variables::
* @t{gatbps} Asynchronous Events::
* @t{gatbps} Standard Output::
* @t{gatbps} Standard Error::
* @t{gatbps} Output Files::
* @t{gatbps} Exit Status::
* @t{gatbps} Consequences of Errors::
@end menu

@lowersections
@include gatbps-Synopsis.texi

@include gatbps-Description.texi

@include gatbps-Options.texi

@include gatbps-Operands.texi

@include gatbps-Standard-Input.texi

@include gatbps-Input-Files.texi

@include gatbps-Environment-Variables.texi

@include gatbps-Asynchronous-Events.texi

@include gatbps-Standard-Output.texi

@include gatbps-Standard-Error.texi

@include gatbps-Output-Files.texi

@include gatbps-Exit-Status.texi

@include gatbps-Consequences-of-Errors.texi
@raisesections
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
