@node Java Compilation with the GNU Autotools
@chapter Java Compilation with the GNU Autotools

@noindent
GATBPS provides a set of special files for Java compilation with the GNU
Autotools using the standard
@w{@t{javac}}
and
@w{@t{jar}}
tools@.

@sfindex @w{@t{GATBPS_PROG_JAR.@:m4}}
@sfindex @w{@t{GATBPS_PROG_JAVAC.@:m4}}
@include indent.texi
The first step is to set the
@w{@t{JAVAC}}
and
@w{@t{JAR}}
variables to commands that run the
@w{@t{javac}}
and
@w{@t{jar}}
tools in your makefile@.
You can do this by calling the
@w{@t{GATBPS_PROG_JAVAC}}
and
@w{@t{GATBPS_PROG_JAR}}
macros in your
@w{@t{configure.@:ac}}
file@.
These macros are defined by the
@w{@t{GATBPS_PROG_JAVAC.@:m4}}
and
@w{@t{GATBPS_PROG_JAR.@:m4}}
special files@.
They take zero arguments and prepare the variables by calling the
@w{@t{AC_CHECK_PROGS}}
and
@w{@t{AC_ARG_VAR}}
macros@.
If you are using Automake, then this is all you need to do@.
Otherwise, you also need to add the
@w{@t{JAVAC = @@JAVAC@@}}
and
@w{@t{JAR = @@JAR@@}}
lines to your
@w{@t{Makefile.@:in}}
file@.

@include indent.texi
For example, if you are using the
@w{@t{m4}}
directory to hold your macros, then you can use the following commands
to generate the special files:

@example
gatbps m4/GATBPS_PROG_JAVAC.m4
gatbps m4/GATBPS_PROG_JAR.m4
@end example

@noindent
Then you can add the following lines to your
@w{@t{configure.@:ac}}
file to call the macros:

@example
GATBPS_PROG_JAVAC
GATBPS_PROG_JAR
@end example

@noindent
Then you can add the following lines to your
@w{@t{Makefile.@:in}}
file to set the variables if you are not using Automake:

@example
JAVAC = @@JAVAC@@
JAR = @@JAR@@
@end example

@include indent.texi
The
@w{@t{GATBPS_PROG_JAVAC}}
macro also prepares the
@w{@t{JAVACFLAGS}}
and
@w{@t{CLASSPATH}}
variables by calling the
@w{@t{AC_ARG_VAR}}
macro@.
These variables are used when running the
@w{@t{javac}}
tool, so if you are not using Automake, then you should also add the
@w{@t{JAVACFLAGS = @@JAVACFLAGS@@}}
and
@w{@t{CLASSPATH = @@CLASSPATH@@}}
lines to your
@w{@t{Makefile.@:in}}
file@.
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
