@node Special File Reference
@chapter Special File Reference

This section provides a short
description of each special file@.
Along with each
short description is a
cross-reference to where the
full description can be found@.
If a special file
supports comments,
then its short description is also
included in a comment at the top of the file@.
The short descriptions can
also be shown by using the
@w{@t{-@w{-}help=}@i{S}}
option of
@w{@t{gatbps}@.}

@table @asis
@sfindex @w{@t{CC0-1.@:0-appendix.@:texi}}
@item @w{@t{CC0-1.@:0-appendix.@:texi}}
@include ipez.texi
The
@w{@t{CC0-1.@:0-appendix.@:texi}}
special file
is a Texinfo
appendix that contains
the complete text of the
Creative Commons Zero (CC0) 1.@:0
Universal Public Domain Dedication@.
It can be included
in another Texinfo file where
the appendix is desired to appear@.
The appendix is labeled with
@w{@t{@@node Creative Commons Zero 1-0}}
so that it maintains
the usual node structure
and can be cross-referenced@.

For more information, @pxref{Copyright Texts}@.

@sfindex @w{@t{CC0-1.@:0-commit.@:txt}}
@item @w{@t{CC0-1.@:0-commit.@:txt}}
@include ipez.texi
The
@w{@t{CC0-1.@:0-commit.@:txt}}
special file is a commit
message template that states that
the author of the commit has waived
their rights to it by cross-referencing the
@w{@t{CC0-1.@:0.@:txt}}
special file@.
This can be used, for example, with Git's
@w{@t{commit.@:template}}
configuration variable@.

For more information, @pxref{Copyright Texts}@.

@sfindex @w{@t{CC0-1.@:0-copying.@:texi}}
@item @w{@t{CC0-1.@:0-copying.@:texi}}
@include ipez.texi
The
@w{@t{CC0-1.@:0-copying.@:texi}}
special file invokes the
@w{@t{@@copying}}
Texinfo command with a
message stating that the
authors of the manual have
waived their rights to it by
cross-referencing the appendix of the
@w{@t{CC0-1.@:0-appendix.@:texi}}
special file@.
It can be included in
another Texinfo file where the
@w{@t{@@copying}}
command is desired to appear@.

For more information, @pxref{Copyright Texts}@.

@sfindex @w{@t{CC0-1.@:0-file.@:txt}}
@item @w{@t{CC0-1.@:0-file.@:txt}}
@include ipez.texi
The
@w{@t{CC0-1.@:0-file.@:txt}}
special file contains
a message stating that the
authors of the file have waived their
rights to it by cross-referencing the
@w{@t{CC0-1.@:0.@:txt}}
special file@.
This can be used
as a copyright notice
in a wide variety of files@.

For more information, @pxref{Copyright Texts}@.

@sfindex @w{@t{CC0-1.@:0.@:txt}}
@item @w{@t{CC0-1.@:0.@:txt}}
@include ipez.texi
The
@w{@t{CC0-1.@:0.@:txt}}
special file is the
plain text version of the
Creative Commons Zero (CC0) 1.@:0
Universal Public Domain Dedication@.

For more information, @pxref{Copyright Texts}@.

@sfindex @w{@t{TEST_EXIT.@:h}}
@item @w{@t{TEST_EXIT.@:h}}
@include ipez.texi
The
@w{@t{TEST_EXIT.@:h}}
special file is a C header file that defines the
@w{@t{TEST_EXIT_ERROR}@comma{}}
@w{@t{TEST_EXIT_FAIL}@comma{}}
@w{@t{TEST_EXIT_PASS}@comma{}}
and
@w{@t{TEST_EXIT_SKIP}}
macros to
@w{@t{99}@comma{}}
@w{@t{1}@comma{}}
@w{@t{0}@comma{}}
and
@w{@t{77}@comma{}}
respectively@.
These are the exit status values used by GNU Automake for a test suite
with no test protocol@.

@sfindex @w{@t{bdots.@:texi}}
@tmindex @w{@t{@@bdots}}
@item @w{@t{bdots.@:texi}}
@include ipez.texi
The
@w{@t{bdots.@:texi}}
special file defines the
@w{@t{@@bdots@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$1, \ldots, n$
@@end tex
@@ifnottex
1, @@bdots@{@}, @@i@{n@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{dslash.@:texi}}
@tmindex @w{@t{@@dslash}}
@item @w{@t{dslash.@:texi}}
@include ipez.texi
The
@w{@t{dslash.@:texi}}
special file defines the
@w{@t{@@dslash@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x / y$
@@end tex
@@ifnottex
@@i@{x@} @@dslash@{@} @@i@{y@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{gequ.@:texi}}
@tmindex @w{@t{@@gequ}}
@item @w{@t{gequ.@:texi}}
@include ipez.texi
The
@w{@t{gequ.@:texi}}
special file defines the
@w{@t{@@gequ@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x \ge y$
@@end tex
@@ifnottex
@@i@{x@} @@gequ@{@} @@i@{y@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{lcei.@:texi}}
@tmindex @w{@t{@@lcei}}
@item @w{@t{lcei.@:texi}}
@include ipez.texi
The
@w{@t{lcei.@:texi}}
special file defines the
@w{@t{@@lcei@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$\lceil x \rceil$
@@end tex
@@ifnottex
@@lcei@{@}@@i@{x@}@@rcei@{@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{lequ.@:texi}}
@tmindex @w{@t{@@lequ}}
@item @w{@t{lequ.@:texi}}
@include ipez.texi
The
@w{@t{lequ.@:texi}}
special file defines the
@w{@t{@@lequ@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x \le y$
@@end tex
@@ifnottex
@@i@{x@} @@lequ@{@} @@i@{y@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{lflo.@:texi}}
@tmindex @w{@t{@@lflo}}
@item @w{@t{lflo.@:texi}}
@include ipez.texi
The
@w{@t{lflo.@:texi}}
special file defines the
@w{@t{@@lflo@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$\lfloor x \rfloor$
@@end tex
@@ifnottex
@@lflo@{@}@@i@{x@}@@rflo@{@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{math.@:texi}}
@item @w{@t{math.@:texi}}
@include ipez.texi
The
@w{@t{math.@:texi}}
special file is a Texinfo file
that includes every special file
that defines a macro for imitating
the mathematical notation of @TeX{} in
the other output formats@.

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{mdot.@:texi}}
@tmindex @w{@t{@@mdot}}
@item @w{@t{mdot.@:texi}}
@include ipez.texi
The
@w{@t{mdot.@:texi}}
special file defines the
@w{@t{@@mdot@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x \cdot y$
@@end tex
@@ifnottex
@@i@{x@} @@mdot@{@} @@i@{y@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{mdots.@:texi}}
@tmindex @w{@t{@@mdots}}
@item @w{@t{mdots.@:texi}}
@include ipez.texi
The
@w{@t{mdots.@:texi}}
special file defines the
@w{@t{@@mdots@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$1 + \cdots + n$
@@end tex
@@ifnottex
1 + @@mdots@{@} + @@i@{n@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{msign.@:texi}}
@tmindex @w{@t{@@msign}}
@item @w{@t{msign.@:texi}}
@include ipez.texi
The
@w{@t{msign.@:texi}}
special file defines the
@w{@t{@@msign@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x - y$
@@end tex
@@ifnottex
@@i@{x@} @@msign@{@} @@i@{y@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{nequ.@:texi}}
@tmindex @w{@t{@@nequ}}
@item @w{@t{nequ.@:texi}}
@include ipez.texi
The
@w{@t{nequ.@:texi}}
special file defines the
@w{@t{@@nequ@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x \ne y$
@@end tex
@@ifnottex
@@i@{x@} @@nequ@{@} @@i@{y@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{prm.@:texi}}
@tmindex @w{@t{@@prm}}
@item @w{@t{prm.@:texi}}
@include ipez.texi
The
@w{@t{prm.@:texi}}
special file defines the
@w{@t{@@prm@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x'$
@@end tex
@@ifnottex
@@i@{x@}@@prm@{@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{rarrow.@:texi}}
@tmindex @w{@t{@@rarrow}}
@item @w{@t{rarrow.@:texi}}
@include ipez.texi
The
@w{@t{rarrow.@:texi}}
special file defines the
@w{@t{@@rarrow@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$P \rightarrow Q$
@@end tex
@@ifnottex
@@i@{P@} @@rarrow@{@} @@i@{Q@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{rcei.@:texi}}
@tmindex @w{@t{@@rcei}}
@item @w{@t{rcei.@:texi}}
@include ipez.texi
The
@w{@t{rcei.@:texi}}
special file defines the
@w{@t{@@rcei@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$\lceil x \rceil$
@@end tex
@@ifnottex
@@lcei@{@}@@i@{x@}@@rcei@{@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{rflo.@:texi}}
@tmindex @w{@t{@@rflo}}
@item @w{@t{rflo.@:texi}}
@include ipez.texi
The
@w{@t{rflo.@:texi}}
special file defines the
@w{@t{@@rflo@{@}}}
Texinfo macro,
which can be used to
imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$\lfloor x \rfloor$
@@end tex
@@ifnottex
@@lflo@{@}@@i@{x@}@@rflo@{@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{sbs.@:texi}}
@tmindex @w{@t{@@sbs}}
@item @w{@t{sbs.@:texi}}
@include ipez.texi
The
@w{@t{sbs.@:texi}}
special file defines the
@w{@t{@@sbs@{}@i{L}@t{@comma{} }@i{S}@t{@comma{} }@i{R}@t{@}}}
Texinfo macro, which inserts
@w{@i{S}}
as a subscript in the output formats other than @TeX{}@.
@w{@i{L}}
and
@w{@i{R}}
are ignored except in Info and plain text,
in which they are inserted to the left and right of
@w{@i{S}@comma{}}
serving as parentheses@.
This is used to imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x_@{y + z_w@}$
@@end tex
@@ifnottex
@@i@{x@}@@sbs@{(,@@i@{y@} + @@i@{z@}@@sbs@{,@@i@{w@},@},)@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{sh-form.@:sh}}
@item @w{@t{sh-form.@:sh}}
@include ipez.texi
The
@w{@t{sh-form.@:sh}}
special file is a portable
shell script that formats its
input as a shell string literal@.

For more information, @pxref{Invoking @w{@t{sh-form-sh}}}@.

@sfindex @w{@t{sps.@:texi}}
@tmindex @w{@t{@@sps}}
@item @w{@t{sps.@:texi}}
@include ipez.texi
The
@w{@t{sps.@:texi}}
special file defines the
@w{@t{@@sps@{}@i{L}@t{@comma{} }@i{S}@t{@comma{} }@i{R}@t{@}}}
Texinfo macro, which inserts
@w{@i{S}}
as a superscript in the output formats other than @TeX{}@.
@w{@i{L}}
and
@w{@i{R}}
are ignored except in Info and plain text,
in which they are inserted to the left and right of
@w{@i{S}@comma{}}
serving as parentheses@.
This is used to imitate the mathematical
notation of @TeX{} in the other output formats:

@example
@@tex
$x^@{y + z^w@}$
@@end tex
@@ifnottex
@@i@{x@}@@sps@{(,@@i@{y@} + @@i@{z@}@@sps@{,@@i@{w@},@},)@}
@@end ifnottex
@end example

For more information, @pxref{Mathematical Notation in Texinfo}@.

@sfindex @w{@t{texinfo.@:css}}
@item @w{@t{texinfo.@:css}}
@include ipez.texi
The
@w{@t{texinfo.@:css}}
special file is a cascading style sheet that makes Texinfo's HTML output
look more like its
@TeX{}
output@.
It can be used with the
@w{@t{-@w{-}css-include}}
option of
@w{@t{texi2any}}
to embed it into the style sheet of the HTML output@.
@end table
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
