@node Writing Mathematical Symbols
@chapter Writing Mathematical Symbols

@noindent
The following table lists the
macros that have no parameters,
which insert individual symbols@.
Along with each macro
is its corresponding @TeX{} syntax,
the Unicode character that it inserts by default,
and the ASCII alternative that it inserts if the
@w{@t{insertascii}}
flag is set at its point of inclusion@.
If this manual is translated to
@TeX{}
or without the
@w{@t{insertascii}}
flag set, then the table will also include a column that shows the
symbol of each macro@.

@quotation
@ifnottex
@ifset insertascii
@set HideSymbolColumn
@end ifset
@end ifnottex
@ifset HideSymbolColumn
@include mtvskiptop.texi
@multitable {@t{\longleftrightarrow}} {@t{@@lldarrow}} {Unicode} {@t{floor(}}
@headitem @TeX{} @tab Macro @tab Unicode @tab ASCII
@item @w{@t{'}}
@sfindex @w{@t{prm.@:texi}}
@tmindex @w{@t{@@prm}}
@tab @w{@t{@@prm}}
@tab @w{U+2032}
@tab @w{@t{'}}
@item @w{@t{'@w{'}}}
@sfindex @w{@t{dprm.@:texi}}
@tmindex @w{@t{@@dprm}}
@tab @w{@t{@@dprm}}
@tab @w{U+2033}
@tab @w{@t{'@w{'}}}
@item @w{@t{'@w{'}'}}
@sfindex @w{@t{tprm.@:texi}}
@tmindex @w{@t{@@tprm}}
@tab @w{@t{@@tprm}}
@tab @w{U+2034}
@tab @w{@t{'@w{'}'}}
@item @w{@t{'@w{'}'@w{'}}}
@sfindex @w{@t{qprm.@:texi}}
@tmindex @w{@t{@@qprm}}
@tab @w{@t{@@qprm}}
@tab @w{U+2057}
@tab @w{@t{'@w{'}'@w{'}}}
@item @w{@t{-}}
@sfindex @w{@t{msign.@:texi}}
@tmindex @w{@t{@@msign}}
@tab @w{@t{@@msign}}
@tab @w{U+2212}
@tab @w{@t{-}}
@item @w{@t{/}}
@sfindex @w{@t{dslash.@:texi}}
@tmindex @w{@t{@@dslash}}
@tab @w{@t{@@dslash}}
@tab @w{U+2215}
@tab @w{@t{/}}
@item @w{@t{\cdot}}
@sfindex @w{@t{mdot.@:texi}}
@tmindex @w{@t{@@mdot}}
@tab @w{@t{@@mdot}}
@tab @w{U+22C5}
@tab @w{@t{*}}
@item @w{@t{\cdots}}
@sfindex @w{@t{mdots.@:texi}}
@tmindex @w{@t{@@mdots}}
@tab @w{@t{@@mdots}}
@tab @w{U+22EF}
@tab @w{@t{.@:.@:.@:}}
@item @w{@t{\ge}}
@sfindex @w{@t{gequ.@:texi}}
@tmindex @w{@t{@@gequ}}
@tab @w{@t{@@gequ}}
@tab @w{U+2265}
@tab @w{@t{>=}}
@item @w{@t{\lceil}}
@sfindex @w{@t{lcei.@:texi}}
@tmindex @w{@t{@@lcei}}
@tab @w{@t{@@lcei}}
@tab @w{U+2308}
@tab @w{@t{ceil(}}
@item @w{@t{\ldots}}
@sfindex @w{@t{bdots.@:texi}}
@tmindex @w{@t{@@bdots}}
@tab @w{@t{@@bdots}}
@tab @w{U+2026}
@tab @w{@t{.@:.@:.@:}}
@item @w{@t{\le}}
@sfindex @w{@t{lequ.@:texi}}
@tmindex @w{@t{@@lequ}}
@tab @w{@t{@@lequ}}
@tab @w{U+2264}
@tab @w{@t{<=}}
@item @w{@t{\leftarrow}}
@sfindex @w{@t{larrow.@:texi}}
@tmindex @w{@t{@@larrow}}
@tab @w{@t{@@larrow}}
@tab @w{U+2190}
@tab @w{@t{<-}}
@item @w{@t{\leftrightarrow}}
@sfindex @w{@t{barrow.@:texi}}
@tmindex @w{@t{@@barrow}}
@tab @w{@t{@@barrow}}
@tab @w{U+2194}
@tab @w{@t{<->}}
@item @w{@t{\lfloor}}
@sfindex @w{@t{lflo.@:texi}}
@tmindex @w{@t{@@lflo}}
@tab @w{@t{@@lflo}}
@tab @w{U+230A}
@tab @w{@t{floor(}}
@item @w{@t{\longleftarrow}}
@sfindex @w{@t{llarrow.@:texi}}
@tmindex @w{@t{@@llarrow}}
@tab @w{@t{@@llarrow}}
@tab @w{U+27F5}
@tab @w{@t{<-@w{-}}}
@item @w{@t{\longrightarrow}}
@sfindex @w{@t{lrarrow.@:texi}}
@tmindex @w{@t{@@lrarrow}}
@tab @w{@t{@@lrarrow}}
@tab @w{U+27F6}
@tab @w{@t{-@w{-}>}}
@item @w{@t{\ne}}
@sfindex @w{@t{nequ.@:texi}}
@tmindex @w{@t{@@nequ}}
@tab @w{@t{@@nequ}}
@tab @w{U+2260}
@tab @w{@t{!=}}
@item @w{@t{\rceil}}
@sfindex @w{@t{rcei.@:texi}}
@tmindex @w{@t{@@rcei}}
@tab @w{@t{@@rcei}}
@tab @w{U+2309}
@tab @w{@t{)}}
@item @w{@t{\rfloor}}
@sfindex @w{@t{rflo.@:texi}}
@tmindex @w{@t{@@rflo}}
@tab @w{@t{@@rflo}}
@tab @w{U+230B}
@tab @w{@t{)}}
@item @w{@t{\rightarrow}}
@sfindex @w{@t{rarrow.@:texi}}
@tmindex @w{@t{@@rarrow}}
@tab @w{@t{@@rarrow}}
@tab @w{U+2192}
@tab @w{@t{->}}
@end multitable
@include mtvskipbot.texi
@end ifset
@ifclear HideSymbolColumn
@include mtvskiptop.texi
@multitable {@t{\longleftrightarrow}} {@t{@@lldarrow}} {Unicode} {@t{floor(}} {Symbol}
@headitem @TeX{} @tab Macro @tab Unicode @tab ASCII @tab Symbol
@item @w{@t{'}}
@sfindex @w{@t{prm.@:texi}}
@tmindex @w{@t{@@prm}}
@tab @w{@t{@@prm}}
@tab @w{U+2032}
@tab @w{@t{'}}
@tab
@tex
$'$
@end tex
@ifnottex
@w{@prm{}}
@end ifnottex
@item @w{@t{'@w{'}}}
@sfindex @w{@t{dprm.@:texi}}
@tmindex @w{@t{@@dprm}}
@tab @w{@t{@@dprm}}
@tab @w{U+2033}
@tab @w{@t{'@w{'}}}
@tab
@tex
$''$
@end tex
@ifnottex
@w{@dprm{}}
@end ifnottex
@item @w{@t{'@w{'}'}}
@sfindex @w{@t{tprm.@:texi}}
@tmindex @w{@t{@@tprm}}
@tab @w{@t{@@tprm}}
@tab @w{U+2034}
@tab @w{@t{'@w{'}'}}
@tab
@tex
$'''$
@end tex
@ifnottex
@w{@tprm{}}
@end ifnottex
@item @w{@t{'@w{'}'@w{'}}}
@sfindex @w{@t{qprm.@:texi}}
@tmindex @w{@t{@@qprm}}
@tab @w{@t{@@qprm}}
@tab @w{U+2057}
@tab @w{@t{'@w{'}'@w{'}}}
@tab
@tex
$''''$
@end tex
@ifnottex
@w{@qprm{}}
@end ifnottex
@item @w{@t{-}}
@sfindex @w{@t{msign.@:texi}}
@tmindex @w{@t{@@msign}}
@tab @w{@t{@@msign}}
@tab @w{U+2212}
@tab @w{@t{-}}
@tab
@tex
$-$
@end tex
@ifnottex
@w{@msign{}}
@end ifnottex
@item @w{@t{/}}
@sfindex @w{@t{dslash.@:texi}}
@tmindex @w{@t{@@dslash}}
@tab @w{@t{@@dslash}}
@tab @w{U+2215}
@tab @w{@t{/}}
@tab
@tex
$/$
@end tex
@ifnottex
@w{@dslash{}}
@end ifnottex
@item @w{@t{\cdot}}
@sfindex @w{@t{mdot.@:texi}}
@tmindex @w{@t{@@mdot}}
@tab @w{@t{@@mdot}}
@tab @w{U+22C5}
@tab @w{@t{*}}
@tab
@tex
$\cdot$
@end tex
@ifnottex
@w{@mdot{}}
@end ifnottex
@item @w{@t{\cdots}}
@sfindex @w{@t{mdots.@:texi}}
@tmindex @w{@t{@@mdots}}
@tab @w{@t{@@mdots}}
@tab @w{U+22EF}
@tab @w{@t{.@:.@:.@:}}
@tab
@tex
$\cdots$
@end tex
@ifnottex
@w{@mdots{}}
@end ifnottex
@item @w{@t{\ge}}
@sfindex @w{@t{gequ.@:texi}}
@tmindex @w{@t{@@gequ}}
@tab @w{@t{@@gequ}}
@tab @w{U+2265}
@tab @w{@t{>=}}
@tab
@tex
$\ge$
@end tex
@ifnottex
@w{@gequ{}}
@end ifnottex
@item @w{@t{\lceil}}
@sfindex @w{@t{lcei.@:texi}}
@tmindex @w{@t{@@lcei}}
@tab @w{@t{@@lcei}}
@tab @w{U+2308}
@tab @w{@t{ceil(}}
@tab
@tex
$\lceil$
@end tex
@ifnottex
@w{@lcei{}}
@end ifnottex
@item @w{@t{\ldots}}
@sfindex @w{@t{bdots.@:texi}}
@tmindex @w{@t{@@bdots}}
@tab @w{@t{@@bdots}}
@tab @w{U+2026}
@tab @w{@t{.@:.@:.@:}}
@tab
@tex
$\ldots$
@end tex
@ifnottex
@w{@bdots{}}
@end ifnottex
@item @w{@t{\le}}
@sfindex @w{@t{lequ.@:texi}}
@tmindex @w{@t{@@lequ}}
@tab @w{@t{@@lequ}}
@tab @w{U+2264}
@tab @w{@t{<=}}
@tab
@tex
$\le$
@end tex
@ifnottex
@w{@lequ{}}
@end ifnottex
@item @w{@t{\leftarrow}}
@sfindex @w{@t{larrow.@:texi}}
@tmindex @w{@t{@@larrow}}
@tab @w{@t{@@larrow}}
@tab @w{U+2190}
@tab @w{@t{<-}}
@tab
@tex
$\leftarrow$
@end tex
@ifnottex
@w{@larrow{}}
@end ifnottex
@item @w{@t{\leftrightarrow}}
@sfindex @w{@t{barrow.@:texi}}
@tmindex @w{@t{@@barrow}}
@tab @w{@t{@@barrow}}
@tab @w{U+2194}
@tab @w{@t{<->}}
@tab
@tex
$\leftrightarrow$
@end tex
@ifnottex
@w{@barrow{}}
@end ifnottex
@item @w{@t{\lfloor}}
@sfindex @w{@t{lflo.@:texi}}
@tmindex @w{@t{@@lflo}}
@tab @w{@t{@@lflo}}
@tab @w{U+230A}
@tab @w{@t{floor(}}
@tab
@tex
$\lfloor$
@end tex
@ifnottex
@w{@lflo{}}
@end ifnottex
@item @w{@t{\longleftarrow}}
@sfindex @w{@t{llarrow.@:texi}}
@tmindex @w{@t{@@llarrow}}
@tab @w{@t{@@llarrow}}
@tab @w{U+27F5}
@tab @w{@t{<-@w{-}}}
@tab
@tex
$\longleftarrow$
@end tex
@ifnottex
@w{@llarrow{}}
@end ifnottex
@item @w{@t{\longrightarrow}}
@sfindex @w{@t{lrarrow.@:texi}}
@tmindex @w{@t{@@lrarrow}}
@tab @w{@t{@@lrarrow}}
@tab @w{U+27F6}
@tab @w{@t{-@w{-}>}}
@tab
@tex
$\longrightarrow$
@end tex
@ifnottex
@w{@lrarrow{}}
@end ifnottex
@item @w{@t{\ne}}
@sfindex @w{@t{nequ.@:texi}}
@tmindex @w{@t{@@nequ}}
@tab @w{@t{@@nequ}}
@tab @w{U+2260}
@tab @w{@t{!=}}
@tab
@tex
$\ne$
@end tex
@ifnottex
@w{@nequ{}}
@end ifnottex
@item @w{@t{\rceil}}
@sfindex @w{@t{rcei.@:texi}}
@tmindex @w{@t{@@rcei}}
@tab @w{@t{@@rcei}}
@tab @w{U+2309}
@tab @w{@t{)}}
@tab
@tex
$\rceil$
@end tex
@ifnottex
@w{@rcei{}}
@end ifnottex
@item @w{@t{\rfloor}}
@sfindex @w{@t{rflo.@:texi}}
@tmindex @w{@t{@@rflo}}
@tab @w{@t{@@rflo}}
@tab @w{U+230B}
@tab @w{@t{)}}
@tab
@tex
$\rfloor$
@end tex
@ifnottex
@w{@rflo{}}
@end ifnottex
@item @w{@t{\rightarrow}}
@sfindex @w{@t{rarrow.@:texi}}
@tmindex @w{@t{@@rarrow}}
@tab @w{@t{@@rarrow}}
@tab @w{U+2192}
@tab @w{@t{->}}
@tab
@tex
$\rightarrow$
@end tex
@ifnottex
@w{@rarrow{}}
@end ifnottex
@end multitable
@include mtvskipbot.texi
@end ifclear
@clear HideSymbolColumn
@end quotation
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
