@node Writing Mathematical Symbols
@chapter Writing Mathematical Symbols

@noindent
The following table lists the
macros that have no parameters,
which insert individual symbols@.
Along with each macro
is its corresponding @TeX{} syntax,
the Unicode character that it inserts by default,
and the ASCII alternative that it inserts if the
@w{@t{insertascii}}
flag is set at its point of inclusion@.
If this manual
is translated to
@TeX{} or without the
@w{@t{insertascii}}
flag set,
then the table also
shows the symbol of each macro@.

@quotation
@ifnottex
@ifset insertascii
@set HideSymbols
@end ifset
@end ifnottex
@ifset HideSymbols
@include mtvskiptop.texi
@multitable {@t{\longleftrightarrow}} {@t{@@lldarrow@{@}}} {Unicode} {@t{floor(}}
@headitem @TeX{} @tab Macro @tab Unicode @tab ASCII
@item @t{'}
@sfindex @w{@t{prm.@:texi}}
@tmindex @w{@t{@@prm}}
@tab @t{@@prm@{@}}
@tab U+2032
@tab @t{'}
@item @t{'@w{'}}
@sfindex @w{@t{dprm.@:texi}}
@tmindex @w{@t{@@dprm}}
@tab @t{@@dprm@{@}}
@tab U+2033
@tab @t{'@w{'}}
@item @t{-}
@sfindex @w{@t{msign.@:texi}}
@tmindex @w{@t{@@msign}}
@tab @t{@@msign@{@}}
@tab U+2212
@tab @t{-}
@item @t{/}
@sfindex @w{@t{dslash.@:texi}}
@tmindex @w{@t{@@dslash}}
@tab @t{@@dslash@{@}}
@tab U+2215
@tab @t{/}
@item @t{\cdot}
@sfindex @w{@t{mdot.@:texi}}
@tmindex @w{@t{@@mdot}}
@tab @t{@@mdot@{@}}
@tab U+22C5
@tab @t{*}
@item @t{\cdots}
@sfindex @w{@t{mdots.@:texi}}
@tmindex @w{@t{@@mdots}}
@tab @t{@@mdots@{@}}
@tab U+22EF
@tab @t{.@:.@:.@:}
@item @t{\ge}
@sfindex @w{@t{gequ.@:texi}}
@tmindex @w{@t{@@gequ}}
@tab @t{@@gequ@{@}}
@tab U+2265
@tab @t{>=}
@item @t{\lceil}
@sfindex @w{@t{lcei.@:texi}}
@tmindex @w{@t{@@lcei}}
@tab @t{@@lcei@{@}}
@tab U+2308
@tab @t{ceil(}
@item @t{\ldots}
@sfindex @w{@t{bdots.@:texi}}
@tmindex @w{@t{@@bdots}}
@tab @t{@@bdots@{@}}
@tab U+2026
@tab @t{.@:.@:.@:}
@item @t{\le}
@sfindex @w{@t{lequ.@:texi}}
@tmindex @w{@t{@@lequ}}
@tab @t{@@lequ@{@}}
@tab U+2264
@tab @t{<=}
@item @t{\leftarrow}
@sfindex @w{@t{larrow.@:texi}}
@tmindex @w{@t{@@larrow}}
@tab @t{@@larrow@{@}}
@tab U+2190
@tab @t{<-}
@item @t{\lfloor}
@sfindex @w{@t{lflo.@:texi}}
@tmindex @w{@t{@@lflo}}
@tab @t{@@lflo@{@}}
@tab U+230A
@tab @t{floor(}
@item @t{\longleftarrow}
@sfindex @w{@t{llarrow.@:texi}}
@tmindex @w{@t{@@llarrow}}
@tab @t{@@llarrow@{@}}
@tab U+27F5
@tab @t{<-@w{-}}
@item @t{\ne}
@sfindex @w{@t{nequ.@:texi}}
@tmindex @w{@t{@@nequ}}
@tab @t{@@nequ@{@}}
@tab U+2260
@tab @t{!=}
@item @t{\rceil}
@sfindex @w{@t{rcei.@:texi}}
@tmindex @w{@t{@@rcei}}
@tab @t{@@rcei@{@}}
@tab U+2309
@tab @t{)}
@item @t{\rfloor}
@sfindex @w{@t{rflo.@:texi}}
@tmindex @w{@t{@@rflo}}
@tab @t{@@rflo@{@}}
@tab U+230B
@tab @t{)}
@item @t{\rightarrow}
@sfindex @w{@t{rarrow.@:texi}}
@tmindex @w{@t{@@rarrow}}
@tab @t{@@rarrow@{@}}
@tab U+2192
@tab @t{->}
@end multitable
@include mtvskipbot.texi
@end ifset
@ifclear HideSymbols
@include mtvskiptop.texi
@multitable {@t{\longleftrightarrow}} {@t{@@lldarrow@{@}}} {Unicode} {@t{floor(}} {Symbol}
@headitem @TeX{} @tab Macro @tab Unicode @tab ASCII @tab Symbol
@item @t{'}
@sfindex @w{@t{prm.@:texi}}
@tmindex @w{@t{@@prm}}
@tab @t{@@prm@{@}}
@tab U+2032
@tab @t{'}
@tab
@tex
$'$
@end tex
@ifnottex
@w{@prm{}}
@end ifnottex
@item @t{'@w{'}}
@sfindex @w{@t{dprm.@:texi}}
@tmindex @w{@t{@@dprm}}
@tab @t{@@dprm@{@}}
@tab U+2033
@tab @t{'@w{'}}
@tab
@tex
$''$
@end tex
@ifnottex
@w{@dprm{}}
@end ifnottex
@item @t{-}
@sfindex @w{@t{msign.@:texi}}
@tmindex @w{@t{@@msign}}
@tab @t{@@msign@{@}}
@tab U+2212
@tab @t{-}
@tab
@tex
$-$
@end tex
@ifnottex
@w{@msign{}}
@end ifnottex
@item @t{/}
@sfindex @w{@t{dslash.@:texi}}
@tmindex @w{@t{@@dslash}}
@tab @t{@@dslash@{@}}
@tab U+2215
@tab @t{/}
@tab
@tex
$/$
@end tex
@ifnottex
@w{@dslash{}}
@end ifnottex
@item @t{\cdot}
@sfindex @w{@t{mdot.@:texi}}
@tmindex @w{@t{@@mdot}}
@tab @t{@@mdot@{@}}
@tab U+22C5
@tab @t{*}
@tab
@tex
$\cdot$
@end tex
@ifnottex
@w{@mdot{}}
@end ifnottex
@item @t{\cdots}
@sfindex @w{@t{mdots.@:texi}}
@tmindex @w{@t{@@mdots}}
@tab @t{@@mdots@{@}}
@tab U+22EF
@tab @t{.@:.@:.@:}
@tab
@tex
$\cdots$
@end tex
@ifnottex
@w{@mdots{}}
@end ifnottex
@item @t{\ge}
@sfindex @w{@t{gequ.@:texi}}
@tmindex @w{@t{@@gequ}}
@tab @t{@@gequ@{@}}
@tab U+2265
@tab @t{>=}
@tab
@tex
$\ge$
@end tex
@ifnottex
@w{@gequ{}}
@end ifnottex
@item @t{\lceil}
@sfindex @w{@t{lcei.@:texi}}
@tmindex @w{@t{@@lcei}}
@tab @t{@@lcei@{@}}
@tab U+2308
@tab @t{ceil(}
@tab
@tex
$\lceil$
@end tex
@ifnottex
@w{@lcei{}}
@end ifnottex
@item @t{\ldots}
@sfindex @w{@t{bdots.@:texi}}
@tmindex @w{@t{@@bdots}}
@tab @t{@@bdots@{@}}
@tab U+2026
@tab @t{.@:.@:.@:}
@tab
@tex
$\ldots$
@end tex
@ifnottex
@w{@bdots{}}
@end ifnottex
@item @t{\le}
@sfindex @w{@t{lequ.@:texi}}
@tmindex @w{@t{@@lequ}}
@tab @t{@@lequ@{@}}
@tab U+2264
@tab @t{<=}
@tab
@tex
$\le$
@end tex
@ifnottex
@w{@lequ{}}
@end ifnottex
@item @t{\leftarrow}
@sfindex @w{@t{larrow.@:texi}}
@tmindex @w{@t{@@larrow}}
@tab @t{@@larrow@{@}}
@tab U+2190
@tab @t{<-}
@tab
@tex
$\leftarrow$
@end tex
@ifnottex
@w{@larrow{}}
@end ifnottex
@item @t{\lfloor}
@sfindex @w{@t{lflo.@:texi}}
@tmindex @w{@t{@@lflo}}
@tab @t{@@lflo@{@}}
@tab U+230A
@tab @t{floor(}
@tab
@tex
$\lfloor$
@end tex
@ifnottex
@w{@lflo{}}
@end ifnottex
@item @t{\longleftarrow}
@sfindex @w{@t{llarrow.@:texi}}
@tmindex @w{@t{@@llarrow}}
@tab @t{@@llarrow@{@}}
@tab U+27F5
@tab @t{<-@w{-}}
@tab
@tex
$\longleftarrow$
@end tex
@ifnottex
@w{@llarrow{}}
@end ifnottex
@item @t{\ne}
@sfindex @w{@t{nequ.@:texi}}
@tmindex @w{@t{@@nequ}}
@tab @t{@@nequ@{@}}
@tab U+2260
@tab @t{!=}
@tab
@tex
$\ne$
@end tex
@ifnottex
@w{@nequ{}}
@end ifnottex
@item @t{\rceil}
@sfindex @w{@t{rcei.@:texi}}
@tmindex @w{@t{@@rcei}}
@tab @t{@@rcei@{@}}
@tab U+2309
@tab @t{)}
@tab
@tex
$\rceil$
@end tex
@ifnottex
@w{@rcei{}}
@end ifnottex
@item @t{\rfloor}
@sfindex @w{@t{rflo.@:texi}}
@tmindex @w{@t{@@rflo}}
@tab @t{@@rflo@{@}}
@tab U+230B
@tab @t{)}
@tab
@tex
$\rfloor$
@end tex
@ifnottex
@w{@rflo{}}
@end ifnottex
@item @t{\rightarrow}
@sfindex @w{@t{rarrow.@:texi}}
@tmindex @w{@t{@@rarrow}}
@tab @t{@@rarrow@{@}}
@tab U+2192
@tab @t{->}
@tab
@tex
$\rightarrow$
@end tex
@ifnottex
@w{@rarrow{}}
@end ifnottex
@end multitable
@include mtvskipbot.texi
@end ifclear
@clear HideSymbols
@end quotation
@ifxml
@ifnotxml
@c
@c The authors of this file have waived all copyright and
@c related or neighboring rights to the extent permitted by
@c law as described by the CC0 1.0 Universal Public Domain
@c Dedication. You should have received a copy of the full
@c dedication along with this file, typically as a file
@c named <CC0-1.0.txt>. If not, it may be available at
@c <https://creativecommons.org/publicdomain/zero/1.0/>.
@c
@end ifnotxml
@end ifxml
